/**
 * Shared Shopping-List PDF builder. Extracted from AIConceptsPage so both the
 * fresh-generation "Download PDF" and the saved-item Library download produce the
 * exact same document. `results` is the shoppingResults groups array (each group:
 * { item: {category, description}, products | byRetailer }).
 */

export interface ShoppingProduct {
  title: string;
  source?: string;
  price?: string;
  link?: string;
}

/** Normalize a group into a flat product list (paid uses `products`, free uses `byRetailer`). */
export function normalizeProducts(group: any): ShoppingProduct[] {
  if (group?.products && group.products.length > 0) return group.products;
  if (group?.byRetailer) {
    return group.byRetailer
      .filter((e: any) => e.product)
      .map((e: any) => ({ ...e.product, source: e.retailer }));
  }
  return [];
}

export async function buildShoppingListPdf(
  results: any[],
  opts: { conceptImage?: string | null; filename?: string } = {}
): Promise<void> {
  const { jsPDF } = await import('jspdf');
  const conceptImage = opts.conceptImage || null;

  const doc = new jsPDF({ orientation: 'p', unit: 'mm', format: 'a4' });
  const pageW = 210;
  const margin = 14;
  const contentW = pageW - margin * 2;
  let y = margin;

  // ── Header ──
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(10, 10, 10);
  doc.text('DESIGNATURE', margin, y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(150, 100, 80);
  doc.text('ONLINE INTERIOR DESIGN STUDIO', margin, y + 5);
  doc.setTextColor(150, 150, 150);
  doc.text('designature.studio', pageW - margin, y + 2, { align: 'right' });
  y += 12;

  // ── Concept image ──
  if (conceptImage) {
    try {
      const imgH = Math.round(contentW * 0.5);
      doc.addImage(conceptImage, 'JPEG', margin, y, contentW, imgH);
      y += imgH + 4;
    } catch {
      /* skip if image fails */
    }
  }

  // ── Title ──
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(10, 10, 10);
  doc.text('Shopping List', margin, y);
  y += 2;
  doc.setDrawColor(196, 97, 58);
  doc.setLineWidth(0.5);
  doc.line(margin, y, margin + contentW, y);
  y += 6;

  // ── Products ──
  for (const group of results) {
    const products = normalizeProducts(group);
    if (products.length === 0) continue;

    // Category header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(10, 10, 10);
    doc.text(group.item.category.toUpperCase(), margin, y);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(150, 150, 150);
    doc.text(
      '— ' + group.item.description,
      margin + doc.getTextWidth(group.item.category.toUpperCase()) + 3,
      y
    );
    y += 5;

    for (const product of products) {
      if (y > 265) {
        doc.addPage();
        y = margin;
      }

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(10, 10, 10);
      const titleLines = doc.splitTextToSize(product.title, contentW - 50);
      doc.text(titleLines[0], margin + 3, y);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(120, 120, 120);
      doc.text(product.source || '', pageW - margin - 35, y);
      if (product.price) {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(10, 10, 10);
        doc.text(product.price, pageW - margin, y, { align: 'right' });
      }
      y += 4;

      if (product.link && product.link !== '#') {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(7);
        doc.setTextColor(0, 71, 171);
        const label = `View at ${product.source || 'retailer'} →`;
        doc.textWithLink(label, margin + 3, y, { url: product.link });
        y += 5;
      }

      doc.setDrawColor(220, 220, 220);
      doc.setLineWidth(0.2);
      doc.line(margin, y, margin + contentW, y);
      y += 3;
    }
    y += 3;
  }

  // ── Footer ──
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(180, 180, 180);
  doc.text(
    'Generated by Designature Studio AI · designature.studio · Prices and availability may vary.',
    pageW / 2,
    290,
    { align: 'center' }
  );

  doc.save(opts.filename || 'Designature_Shopping_List.pdf');
}
