/**
 * Shared Shopping-List PDF builder. Extracted from AIConceptsPage so both the
 * fresh-generation "Download PDF" and the saved-item Library download produce the
 * exact same document. `results` is the shoppingResults groups array (each group:
 * { item: {category, description}, products | byRetailer }).
 */

export interface ShoppingProduct {
  title: string;
  source?: string;
  price?: string;
  link?: string;
}

// Brand rule: every generated document carries the latest Cloudinary logo. The
// brand asset is an SVG, so we deliver it rasterized (f_png) for jsPDF's addImage.
const LOGO_HORIZONTAL_LIGHT_PNG =
  'https://res.cloudinary.com/dys2k5muv/image/upload/f_png,w_600/v1779686901/brand/designature-horizontal-oxide-rust.svg';
const LOGO_ASPECT = 820 / 250; // horizontal logo native ratio (w/h)

/** Fetch a URL and return it as a data URL (for jsPDF). Null on any failure. */
async function fetchAsDataUrl(url: string): Promise<string | null> {
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const blob = await res.blob();
    return await new Promise<string | null>((resolve) => {
      const fr = new FileReader();
      fr.onload = () => resolve(fr.result as string);
      fr.onerror = () => resolve(null);
      fr.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

/** Normalize a group into a flat product list (paid uses `products`, free uses `byRetailer`). */
export function normalizeProducts(group: any): ShoppingProduct[] {
  if (group?.products && group.products.length > 0) return group.products;
  if (group?.byRetailer) {
    return group.byRetailer
      .filter((e: any) => e.product)
      .map((e: any) => ({ ...e.product, source: e.retailer }));
  }
  return [];
}

export async function buildShoppingListPdf(
  results: any[],
  opts: { conceptImage?: string | null; filename?: string } = {}
): Promise<void> {
  const { jsPDF } = await import('jspdf');
  const conceptImage = opts.conceptImage || null;

  const doc = new jsPDF({ orientation: 'p', unit: 'mm', format: 'a4' });
  const pageW = 210;
  const margin = 14;
  const contentW = pageW - margin * 2;
  let y = margin;

  // ── Header (brand logo — always, per brand rule) ──
  const logoData = await fetchAsDataUrl(LOGO_HORIZONTAL_LIGHT_PNG);
  if (logoData) {
    try {
      const logoH = 9; // mm
      doc.addImage(logoData, 'PNG', margin, y, logoH * LOGO_ASPECT, logoH);
    } catch {
      // rasterization/addImage failed — fall back to the wordmark text
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(18);
      doc.setTextColor(10, 10, 10);
      doc.text('DESIGNATURE', margin, y + 6);
    }
  } else {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.setTextColor(10, 10, 10);
    doc.text('DESIGNATURE', margin, y + 6);
  }
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(150, 100, 80);
  doc.text('ONLINE INTERIOR DESIGN STUDIO', margin, y + 13);
  doc.setTextColor(150, 150, 150);
  doc.text('designature.studio', pageW - margin, y + 4, { align: 'right' });
  y += 20;

  // ── Concept image (aspect-preserved, capped so it never overflows) ──
  if (conceptImage) {
    try {
      const props = doc.getImageProperties(conceptImage);
      let imgW = contentW;
      let imgH = contentW * (props.height / props.width);
      const MAX_H = 120; // mm
      if (imgH > MAX_H) {
        imgH = MAX_H;
        imgW = imgH * (props.width / props.height);
      }
      const imgX = margin + (contentW - imgW) / 2;
      doc.addImage(conceptImage, 'JPEG', imgX, y, imgW, imgH);
      y += imgH + 5;
    } catch {
      /* skip if image fails */
    }
  }

  // ── Title ──
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(10, 10, 10);
  doc.text('Shopping List', margin, y);
  y += 2;
  doc.setDrawColor(196, 97, 58);
  doc.setLineWidth(0.5);
  doc.line(margin, y, margin + contentW, y);
  y += 6;

  // Page footer — drawn on every page (before each page break + on the last page).
  const drawFooter = () => {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(180, 180, 180);
    doc.text(
      'Generated by Designature Studio AI · designature.studio · Prices and availability may vary.',
      pageW / 2,
      290,
      { align: 'center' }
    );
  };

  // ── Products — one category per page ──
  // The first category shares page 1 with the header + hero; every subsequent
  // category starts on its own fresh page.
  let firstCategory = true;
  for (const group of results) {
    const products = normalizeProducts(group);
    if (products.length === 0) continue;

    if (!firstCategory) {
      drawFooter();
      doc.addPage();
      y = margin;
    }
    firstCategory = false;

    // Category header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(10, 10, 10);
    doc.text(group.item.category.toUpperCase(), margin, y);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(150, 150, 150);
    doc.text(
      '— ' + group.item.description,
      margin + doc.getTextWidth(group.item.category.toUpperCase()) + 3,
      y
    );
    y += 6;

    for (const product of products) {
      // Safety break only if a single category is unusually long.
      if (y > 270) {
        drawFooter();
        doc.addPage();
        y = margin;
      }

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(10, 10, 10);
      const titleLines = doc.splitTextToSize(product.title, contentW - 50);
      doc.text(titleLines[0], margin + 3, y);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(120, 120, 120);
      doc.text(product.source || '', pageW - margin - 35, y);
      if (product.price) {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(10, 10, 10);
        doc.text(product.price, pageW - margin, y, { align: 'right' });
      }
      y += 4;

      if (product.link && product.link !== '#') {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(7);
        doc.setTextColor(0, 71, 171);
        // Plain ASCII only — jsPDF's helvetica (WinAnsi) renders "→" as garbage.
        const label = `View at ${product.source || 'retailer'}`;
        doc.textWithLink(label, margin + 3, y, { url: product.link });
        y += 5;
      }

      doc.setDrawColor(220, 220, 220);
      doc.setLineWidth(0.2);
      doc.line(margin, y, margin + contentW, y);
      y += 3;
    }
  }

  drawFooter(); // final page

  doc.save(opts.filename || 'Designature_Shopping_List.pdf');
}
