# -*- coding: utf-8 -*-
"""Per-photo measurability judgements for _Inputs/source-rooms (67 files).

Columns
  n        stable index (matches thumbs/NN_*.jpg and rooms_exif.json)
  room     room type
  src      phone | dslr | listing | render3d | ai-gen | screenshot | whatsapp
  state    shell | construction | empty | light | furnished | cluttered | detail
  walls    unfinished | finished | tiled | panelled | block
  ceil     unfinished | flat | grid | slab | tray | beamed | sloped
  floor    screed | tile | plank | parquet | carpet | none
  view     detail | 1wall | 2wall | 3wall
  clean    what the redesign must strip before restyling
  rulers   metric references actually visible in THIS frame
  method   recommended primary measurement route (see LADDER)
  conf     high | med | low | none  -- honest expected accuracy of `method`
  flags    anything that changes the product's behaviour
"""

LADDER = {
    "R-CEIL":  "Suspended-ceiling grid — 600x600 / 600x1200 mm (2'x2' / 2'x4'). Rigid, planar, orthogonal, spans the whole room.",
    "R-TILE":  "Floor or wall tile grid on a known module (600/450/300 mm; herringbone parquet block).",
    "R-PLANK": "Constant-width floor planks — counts across a run. Module varies by product, so a cross-check, not a primary.",
    "R-OBJ":   "Standard object of known size: door leaf, radiator, kitchen module, WC, bath, brick course, CMU block, outlet height.",
    "C-VP":    "Vanishing-point calibration from EXIF focal length + camera height. Needs two visible floor-wall corners.",
    "C-TAP":   "User taps two points on the floor and types the real distance. Always available. The floor of the ladder.",
    "D-MONO":  "Monocular metric depth (Depth Pro / UniDepth v2). Estimate only. 5-10% relative error = 20-40 cm on a 4 m wall.",
    "X":       "Not measurable and not designable — reject or route elsewhere.",
}

ROWS = [
 dict(n=1,  room="Living room", src="phone", state="cluttered", walls="finished", ceil="flat", floor="plank", view="3wall",
      clean="sectional, ottoman, toys, backpacks + shoes on the floor", rulers=["PLANK","WIN","OUTLET"], method="C-TAP + R-PLANK", conf="med",
      flags=["EXIF orientation 6 - portrait", "iPhone 13 Pro, f=26mm eq known", "same room as 7 and 48"]),
 dict(n=2,  room="Kitchen", src="render3d", state="furnished", walls="finished", ceil="flat", floor="tile", view="3wall",
      clean="nothing - it is already a proposal, not a room", rulers=["TILE","CAB"], method="R-OBJ (cab 600 deep / 900 high)", conf="high",
      flags=["NOT A PHOTOGRAPH - a 3D render", "ideal pinhole lens, so C-VP is exact", "users will upload renders; decide what that means"]),
 dict(n=3,  room="Living / dining", src="dslr", state="empty", walls="finished", ceil="flat", floor="plank", view="3wall",
      clean="nothing", rulers=["PLANK","OUTLET","CAB"], method="C-VP + R-OBJ", conf="high",
      flags=["Canon 5D II @16mm - very wide, undistort first", "kitchen visible through the opening = second room in frame"]),
 dict(n=4,  room="Bathroom", src="phone", state="shell", walls="unfinished", ceil="flat", floor="tile", view="2wall",
      clean="nothing - fixtures already stripped", rulers=["TILE","DOOR"], method="R-TILE + R-OBJ (door)", conf="high",
      flags=["mid-demolition: gouged plaster, capped services", "EXIF orientation 6"]),
 dict(n=5,  room="Bathroom", src="phone", state="light", walls="tiled", ceil="flat", floor="tile", view="2wall",
      clean="shower curtain", rulers=["TUB","TILE"], method="R-OBJ (bath = 1700 mm)", conf="high",
      flags=["a bathtub is the most reliable ruler that exists in a bathroom", "EXIF orientation 6"]),
 dict(n=6,  room="Bedroom (master)", src="phone", state="empty", walls="finished", ceil="tray", floor="carpet", view="3wall",
      clean="nothing", rulers=["WIN","OUTLET"], method="C-VP, then C-TAP", conf="med",
      flags=["CARPET = no floor ruler at all", "tray ceiling: ceiling height is not one number"]),
 dict(n=7,  room="Living room", src="phone", state="furnished", walls="finished", ceil="flat", floor="plank", view="3wall",
      clean="sectional, armchair, TV, mantel clutter", rulers=["PLANK","OUTLET","WIN"], method="R-PLANK + C-TAP", conf="med",
      flags=["same room as 1 and 48 - a natural multi-view test case"]),
 dict(n=8,  room="(corner detail)", src="phone", state="detail", walls="finished", ceil="none", floor="plank", view="detail",
      clean="n/a", rulers=["PLANK"], method="X", conf="none",
      flags=["NOT A ROOM VIEW - a close-up of a cluttered corner", "belongs in the negative set: the tool must refuse this politely"]),
 dict(n=9,  room="Living room", src="phone", state="light", walls="finished", ceil="flat", floor="plank", view="2wall",
      clean="TV on a trestle table, bags", rulers=["PLANK","TV","OUTLET"], method="R-PLANK + C-TAP", conf="med",
      flags=["dark olive accent wall - restyle must not read it as shadow", "same room as 16"]),
 dict(n=10, room="Office / reception", src="dslr", state="furnished", walls="finished", ceil="flat", floor="tile", view="3wall",
      clean="sofa, armchair, meeting table + chairs", rulers=["TILE","DOOR"], method="R-TILE (600 grid)", conf="high",
      flags=["studio-shot, retouched Nikon", "Armenian commercial interior - our actual market"]),
 dict(n=11, room="Office", src="dslr", state="light", walls="finished", ceil="flat", floor="tile", view="3wall",
      clean="desk, chair, monitor", rulers=["TILE","RAD","WIN"], method="R-TILE (600 grid)", conf="high",
      flags=["radiator under the window = second independent ruler"]),
 dict(n=12, room="Office", src="dslr", state="light", walls="finished", ceil="flat", floor="tile", view="3wall",
      clean="desk, chair, beanbag, AC unit stays (it is a service)", rulers=["TILE","AC"], method="R-TILE (600 grid)", conf="high",
      flags=["split AC = fixed service, KEEP per the AI-016 keep/discard rule"]),
 dict(n=13, room="Lounge / hall", src="dslr", state="light", walls="finished", ceil="flat", floor="tile", view="3wall",
      clean="rocking chair, round table, TV box, signage", rulers=["TILE","DOOR","RAD"], method="R-TILE", conf="high",
      flags=["marble-clad fireplace = fixed feature, KEEP", "French doors give a second ruler"]),
 dict(n=14, room="Kitchen", src="dslr", state="furnished", walls="finished", ceil="flat", floor="tile", view="3wall",
      clean="bar stools, chairs, small appliances", rulers=["TILE","CAB","FRIDGE"], method="R-OBJ (cab modules) + R-TILE", conf="high",
      flags=["kitchen: AI-016 declines it as a wet room, Redesign must NOT"]),
 dict(n=15, room="Bathroom", src="phone", state="furnished", walls="tiled", ceil="flat", floor="tile", view="3wall",
      clean="cleaning bottles, basket, brush, towels", rulers=["TILE","WC","TUB"], method="R-TILE (wall + floor)", conf="high",
      flags=["wall tile AND floor tile agree = self-checking", "EXIF orientation 6"]),
 dict(n=16, room="Living room", src="phone", state="light", walls="finished", ceil="flat", floor="plank", view="2wall",
      clean="boxes, baskets, laundry, cables", rulers=["PLANK","TV","WIN"], method="C-TAP", conf="med",
      flags=["same room as 9", "one huge blank accent wall - the AI-029 single-wall failure mode"]),
 dict(n=17, room="Bathroom", src="phone", state="furnished", walls="finished", ceil="flat", floor="tile", view="2wall",
      clean="toiletries, bath mat, basket", rulers=["TILE","RAD","DOOR","WIN"], method="R-OBJ (radiator, door) + C-TAP", conf="med",
      flags=["tiles laid DIAGONALLY - grid detection must handle 45 degrees"]),
 dict(n=18, room="Living room (shell)", src="dslr", state="shell", walls="unfinished", ceil="unfinished", floor="screed", view="3wall",
      clean="plaster sacks, boards, bucket, trowel", rulers=["RAD","WIN","DOOR"], method="R-OBJ (radiator, window) + C-TAP", conf="med",
      flags=["the canonical Journal 'before' room", "SHELL is the Armenian default state - no tile, no plank, no trim"]),
 dict(n=19, room="Living room", src="phone", state="empty", walls="finished", ceil="flat", floor="plank", view="2wall",
      clean="pots on the sill", rulers=["RAD","WIN","PLANK"], method="R-OBJ (radiator run)", conf="med",
      flags=["a 4-panel window wall and almost nothing else - depth is barely observable"]),
 dict(n=20, room="Bedroom (shell)", src="ai-gen", state="shell", walls="unfinished", ceil="unfinished", floor="screed", view="3wall",
      clean="n/a", rulers=["WIN"], method="X for measurement", conf="none",
      flags=["AI-GENERATED - it has no true dimensions to recover", "must be detected and labelled, never measured"]),
 dict(n=21, room="Bedroom", src="ai-gen", state="empty", walls="finished", ceil="flat", floor="plank", view="3wall",
      clean="n/a", rulers=["RAD","DOOR","PLANK"], method="X for measurement", conf="none",
      flags=["AI-GENERATED", "looks perfectly measurable, which is exactly the danger"]),
 dict(n=22, room="Living room", src="ai-gen", state="empty", walls="finished", ceil="beamed", floor="parquet", view="3wall",
      clean="n/a", rulers=["PARQUET","WIN"], method="X for measurement", conf="none",
      flags=["AI-GENERATED", "herringbone + beams + stair: geometrically plausible, physically invented"]),
 dict(n=23, room="Living room", src="ai-gen", state="empty", walls="finished", ceil="beamed", floor="plank", view="2wall",
      clean="n/a", rulers=["PLANK"], method="X for measurement", conf="none",
      flags=["AI-GENERATED", "mezzanine + ladder"]),
 dict(n=24, room="Office (small)", src="phone", state="empty", walls="finished", ceil="flat", floor="plank", view="3wall",
      clean="console table, bin", rulers=["DOOR","PLANK","OUTLET"], method="R-OBJ (door leaf) after undistort", conf="med",
      flags=["ULTRA-WIDE 13mm equiv - heavy barrel distortion, undistort BEFORE anything", "same room as 25"]),
 dict(n=25, room="Office (small)", src="phone", state="empty", walls="finished", ceil="flat", floor="plank", view="3wall",
      clean="console table", rulers=["DOOR","PLANK"], method="R-OBJ (door leaf) after undistort", conf="med",
      flags=["second view of 24 - two views of one room is the cheapest accuracy upgrade available"]),
 dict(n=26, room="Office (co-working)", src="phone", state="light", walls="finished", ceil="grid", floor="plank", view="3wall",
      clean="trestle desks, stacking chairs, monitor", rulers=["CEIL","PLANK"], method="R-CEIL (2'x4' grid)", conf="high",
      flags=["suspended ceiling grid = the single best ruler in this whole corpus", "13mm ultra-wide, undistort"]),
 dict(n=27, room="Office (co-working)", src="phone", state="light", walls="finished", ceil="grid", floor="plank", view="3wall",
      clean="desks, chairs", rulers=["CEIL","DOOR","PLANK"], method="R-CEIL", conf="high", flags=["second view of 26"]),
 dict(n=28, room="Office (co-working)", src="phone", state="light", walls="finished", ceil="grid", floor="plank", view="3wall",
      clean="desks, chairs, bags", rulers=["CEIL","PLANK"], method="R-CEIL", conf="high", flags=["third view of 26 - a 3-view set"]),
 dict(n=29, room="Office", src="phone", state="cluttered", walls="finished", ceil="grid", floor="carpet", view="3wall",
      clean="desk, chairs, copier, boxes, wall planner", rulers=["CEIL","CARPETTILE"], method="R-CEIL", conf="high",
      flags=["carpet TILES are 500x500 - carpet is not always ruler-less"]),
 dict(n=30, room="Office", src="phone", state="cluttered", walls="finished", ceil="grid", floor="carpet", view="3wall",
      clean="desks, chairs, printer, cartons", rulers=["CEIL","DOOR"], method="R-CEIL", conf="high", flags=["second view of 29"]),
 dict(n=31, room="Store room", src="phone", state="empty", walls="finished", ceil="grid", floor="plank", view="3wall",
      clean="nothing", rulers=["CEIL","PLANK"], method="R-CEIL", conf="high",
      flags=["narrow corridor-shaped room", "EXIF orientation 6", "exposed duct = service, KEEP"]),
 dict(n=32, room="Circulation / lobby", src="phone", state="light", walls="finished", ceil="grid", floor="plank", view="3wall",
      clean="water bottles, fan, cabinet", rulers=["CEIL","DOOR"], method="R-CEIL", conf="high", flags=["EXIF orientation 6"]),
 dict(n=33, room="Office", src="phone", state="furnished", walls="finished", ceil="flat", floor="plank", view="3wall",
      clean="two desks, chairs, monitors, wall planner", rulers=["DOOR","PLANK"], method="R-OBJ (door) + R-PLANK", conf="med",
      flags=["flat ceiling here, grid next door - ruler availability changes room by room in ONE building"]),
 dict(n=34, room="Office", src="phone", state="furnished", walls="finished", ceil="flat", floor="plank", view="3wall",
      clean="desks, chairs, monitors, TV stand", rulers=["PLANK","OUTLET"], method="R-PLANK + C-TAP", conf="med", flags=["second view of 33"]),
 dict(n=35, room="Office", src="phone", state="furnished", walls="block", ceil="grid", floor="carpet", view="3wall",
      clean="desk, folding chairs, printer, bin", rulers=["CEIL","CMU"], method="R-CEIL, cross-checked on CMU courses", conf="high",
      flags=["CMU block wall - 8x16in nominal courses are a second, independent ruler", "electrical panel = service, KEEP"]),
 dict(n=36, room="Office", src="phone", state="furnished", walls="block", ceil="grid", floor="carpet", view="3wall",
      clean="desk, chairs, printer, boxes", rulers=["CEIL","CMU","DOOR"], method="R-CEIL", conf="high", flags=["second view of 35"]),
 dict(n=37, room="Bathroom", src="listing", state="light", walls="tiled", ceil="flat", floor="tile", view="2wall",
      clean="soap dispenser", rulers=["TILE","WC","VANITY"], method="R-TILE (large-format wall tile)", conf="high",
      flags=["agency watermark burned into the image", "no EXIF - listing photos are stripped"]),
 dict(n=38, room="Studio living", src="listing", state="furnished", walls="finished", ceil="slab", floor="plank", view="3wall",
      clean="TV, console, armchair, rug, lamp, plant", rulers=["PLANK","WIN","DOOR"], method="R-PLANK + C-TAP", conf="med",
      flags=["exposed concrete slab ceiling - restyle must not 'finish' it", "no EXIF"]),
 dict(n=39, room="Dining / entry", src="listing", state="furnished", walls="finished", ceil="slab", floor="plank", view="2wall",
      clean="glass table, 4 chairs, sideboard", rulers=["DOOR","PLANK"], method="R-OBJ (entry door 2032 mm)", conf="med", flags=["no EXIF"]),
 dict(n=40, room="Kitchen", src="listing", state="furnished", walls="finished", ceil="slab", floor="plank", view="1wall",
      clean="kettle, utensils, coffee machine", rulers=["CAB","MICRO","PLANK"], method="R-OBJ (cabinet modules, 762 mm OTR microwave)", conf="high",
      flags=["a fitted kitchen is a dimensioned catalogue bolted to the wall - the best R-OBJ case there is"]),
 dict(n=41, room="Studio living", src="listing", state="furnished", walls="finished", ceil="slab", floor="plank", view="3wall",
      clean="TV, console, dining set, sofa", rulers=["PLANK","DOOR"], method="R-PLANK + C-TAP", conf="med", flags=["no EXIF"]),
 dict(n=42, room="Kitchen / living", src="listing", state="furnished", walls="finished", ceil="slab", floor="plank", view="3wall",
      clean="dining set, TV, armchair, rug", rulers=["CAB","PLANK"], method="R-OBJ (cabinets)", conf="med",
      flags=["two rooms in one frame - which one is the user asking about?"]),
 dict(n=43, room="Construction site", src="phone", state="construction", walls="block", ceil="unfinished", floor="screed", view="2wall",
      clean="n/a", rulers=["CMU"], method="X", conf="none",
      flags=["NOT A DESIGNABLE ROOM - scaffolding, structure, no enclosure", "negative set"]),
 dict(n=44, room="Construction site", src="phone", state="construction", walls="block", ceil="unfinished", floor="screed", view="2wall",
      clean="n/a", rulers=["CMU","STAIR"], method="X", conf="none", flags=["negative set"]),
 dict(n=45, room="Living room (shell)", src="phone", state="construction", walls="unfinished", ceil="unfinished", floor="screed", view="3wall",
      clean="plasterboard stacks, lifter, tools, debris", rulers=["BOARD","DOOR"], method="R-OBJ (1200x2500 plasterboard) + C-TAP", conf="low",
      flags=["room shape IS legible - this is 'shell mode', not a reject", "ceiling battens exposed: no ceiling plane yet"]),
 dict(n=46, room="Living room (shell)", src="phone", state="construction", walls="unfinished", ceil="unfinished", floor="screed", view="3wall",
      clean="insulation rolls, boards, sacks, tools", rulers=["BOARD","GLAZING"], method="R-OBJ + C-TAP", conf="low", flags=["shell mode"]),
 dict(n=47, room="Glazed facade", src="phone", state="construction", walls="unfinished", ceil="unfinished", floor="screed", view="1wall",
      clean="n/a", rulers=["MULLION"], method="X", conf="none",
      flags=["mostly glazing and scaffold, no readable floor plane", "negative set"]),
 dict(n=48, room="Living room", src="phone", state="cluttered", walls="finished", ceil="flat", floor="plank", view="3wall",
      clean="sectional, toys, bags, shoes, mantel clutter", rulers=["PLANK","WIN","OUTLET"], method="R-PLANK + C-TAP", conf="med",
      flags=["third view of the room in 1 and 7", "EXIF orientation 6"]),
 dict(n=49, room="Kitchen", src="phone", state="cluttered", walls="finished", ceil="flat", floor="tile", view="2wall",
      clean="appliances, boards, bottles, cloths", rulers=["CAB","TILE","SINK"], method="R-OBJ (cabinet modules, 900 worktop)", conf="high",
      flags=["EXIF orientation 6", "L-shaped run - two walls carry dimensioned units"]),
 dict(n=50, room="Hall / landing", src="phone", state="empty", walls="finished", ceil="flat", floor="plank", view="2wall",
      clean="nothing", rulers=["DOOR","PLANK"], method="R-OBJ (door leaf)", conf="high",
      flags=["almost featureless - the DOOR is carrying the entire measurement", "EXIF orientation 6"]),
 dict(n=51, room="Bedroom", src="dslr", state="empty", walls="finished", ceil="flat", floor="tile", view="3wall",
      clean="nothing", rulers=["DOOR","TILE","WIN","OUTLET"], method="R-OBJ (door) + R-TILE", conf="high",
      flags=["DUPLICATE of 61", "15mm equiv - very wide, undistort", "wood-look tile planks: a tile module, not a plank module"]),
 dict(n=52, room="Bedroom", src="dslr", state="empty", walls="finished", ceil="sloped", floor="plank", view="3wall",
      clean="nothing", rulers=["PLANK","WIN","DOOR"], method="C-VP + R-PLANK", conf="high",
      flags=["DUPLICATE of 63", "SLOPED ceiling - ceiling height is a range, not a number"]),
 dict(n=53, room="Living room", src="dslr", state="empty", walls="finished", ceil="flat", floor="tile", view="3wall",
      clean="nothing", rulers=["TILE","DOOR","WIN","OUTLET"], method="R-TILE + R-OBJ", conf="high",
      flags=["DUPLICATE of 62", "THE IDEAL UPLOAD: empty, three walls, both floor corners, floor-to-ceiling visible"]),
 dict(n=54, room="Living room", src="dslr", state="empty", walls="finished", ceil="flat", floor="plank", view="3wall",
      clean="nothing", rulers=["PLANK","DOOR","WIN"], method="R-OBJ (front door) + R-PLANK", conf="high",
      flags=["DUPLICATE of 64", "opening to the entry hall = a second room in frame"]),
 dict(n=55, room="Living room (shell)", src="phone", state="construction", walls="unfinished", ceil="unfinished", floor="screed", view="2wall",
      clean="paint tub, boards, packaging, radiator not yet hung", rulers=["RAD","WIN"], method="R-OBJ (radiator) + C-TAP", conf="low",
      flags=["A PERSON IS IN FRAME - must be removed before any output is shown", "portrait 3:4"]),
 dict(n=56, room="Bedroom (shell)", src="phone", state="construction", walls="unfinished", ceil="unfinished", floor="screed", view="1wall",
      clean="packaging, cable coil", rulers=["WIN"], method="C-TAP only", conf="low",
      flags=["A CHILD IS IN FRAME - hard privacy stop", "single-wall head-on: the AI-029 failure geometry"]),
 dict(n=57, room="Living room", src="phone", state="furnished", walls="finished", ceil="flat", floor="parquet", view="2wall",
      clean="shelving unit, book tower, chair, plants", rulers=["PARQUET","DOOR","RAD"], method="R-OBJ (door) + R-TILE (herringbone block)", conf="high",
      flags=["MASKING TAPE ON THE FLOOR - the client has taped out a furniture footprint by hand. This is our feature, done manually.",
             "EXIF orientation 6", "same apartment as 58, 59, 60"]),
 dict(n=58, room="Living room", src="phone", state="furnished", walls="panelled", ceil="flat", floor="parquet", view="2wall",
      clean="armchair, bar cart, crate table, pouffe, chair, laptop", rulers=["PARQUET","PANEL","DOOR"], method="R-TILE (herringbone) + R-OBJ", conf="high",
      flags=["wainscot panel module is a third ruler", "same apartment as 57, 59, 60"]),
 dict(n=59, room="Living room", src="phone", state="light", walls="panelled", ceil="flat", floor="parquet", view="3wall",
      clean="chair, crate table, pouffe, picture frames on the floor", rulers=["PARQUET","PANEL","DOOR"], method="R-TILE (herringbone) + R-OBJ", conf="high",
      flags=["tape rectangle again", "same apartment as 57, 58, 60"]),
 dict(n=60, room="Living room", src="phone", state="light", walls="finished", ceil="flat", floor="parquet", view="2wall",
      clean="shelving, book tower, chair, chair", rulers=["PARQUET","DOOR","RAD"], method="R-OBJ (door, radiator sections)", conf="high",
      flags=["tape rectangle again", "same apartment as 57, 58, 59"]),
 dict(n=61, room="Bedroom", src="dslr", state="empty", walls="finished", ceil="flat", floor="tile", view="3wall",
      clean="nothing", rulers=["DOOR","TILE"], method="R-OBJ + R-TILE", conf="high", flags=["BYTE-IDENTICAL DUPLICATE of 51"]),
 dict(n=62, room="Living room", src="dslr", state="empty", walls="finished", ceil="flat", floor="tile", view="3wall",
      clean="nothing", rulers=["TILE","DOOR"], method="R-TILE + R-OBJ", conf="high", flags=["BYTE-IDENTICAL DUPLICATE of 53"]),
 dict(n=63, room="Bedroom", src="dslr", state="empty", walls="finished", ceil="sloped", floor="plank", view="3wall",
      clean="nothing", rulers=["PLANK","WIN"], method="C-VP + R-PLANK", conf="high", flags=["BYTE-IDENTICAL DUPLICATE of 52"]),
 dict(n=64, room="Living room", src="dslr", state="empty", walls="finished", ceil="flat", floor="plank", view="3wall",
      clean="nothing", rulers=["PLANK","DOOR"], method="R-OBJ + R-PLANK", conf="high", flags=["BYTE-IDENTICAL DUPLICATE of 54"]),
 dict(n=65, room="Living room", src="screenshot", state="light", walls="finished", ceil="flat", floor="plank", view="1wall",
      clean="table edge, radio, dust sheet", rulers=["BRICK","WIN","BASEBOARD-HEATER"], method="R-OBJ (brick courses)", conf="high",
      flags=["SCREENSHOT - 1026x708, no EXIF, already downscaled", "brick coursing is a superb ruler", "head-on single wall"]),
 dict(n=66, room="Kitchen", src="screenshot", state="cluttered", walls="finished", ceil="flat", floor="none", view="2wall",
      clean="every worktop item, table setting, curtain valance", rulers=["CAB","RANGE","MICRO","BACKSPLASH"], method="R-OBJ (30in range, OTR microwave)", conf="high",
      flags=["SCREENSHOT - no EXIF", "floor is not visible at all - no floor plane, so C-VP and C-TAP both fail"]),
 dict(n=67, room="Kitchen", src="whatsapp", state="construction", walls="finished", ceil="flat", floor="plank", view="2wall",
      clean="packaging, tools, cartons", rulers=["CAB","PLANK","STEP"], method="R-OBJ (island / worktop 900)", conf="med",
      flags=["WHATSAPP: 153 KB for 1200x1600 - the most degraded file in the set, and WhatsApp IS the studio's client channel",
             "TWO PEOPLE IN FRAME", "install in progress - half the kitchen is boxes"]),
]
