
import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

export type Language = 'en' | 'am';
export type Page = 'home' | 'portfolio' | 'project-detail' | 'services' | 'studio' | 'ai-concepts' | 'ai-vision' | 'pricing';
export type PortfolioFilter = 'All' | 'Residential' | 'Commercial';

const STORAGE_KEYS = {
  currentPage: 'ds_current_page',
} as const;

function getInitialPage(): Page {
  const raw = localStorage.getItem(STORAGE_KEYS.currentPage);
  if (!raw) return 'home';
  // Only allow known pages (guards against stale/invalid values)
  const allowed: Page[] = ['home', 'portfolio', 'project-detail', 'services', 'studio', 'ai-concepts', 'ai-vision', 'pricing'];
  return (allowed as string[]).includes(raw) ? (raw as Page) : 'home';
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  currentPage: Page;
  portfolioFilter: PortfolioFilter;
  setPortfolioFilter: (filter: PortfolioFilter) => void;
  selectedProjectId: string | null;
  setSelectedProjectId: (id: string | null) => void;
  navigateTo: (page: Page, projectId?: string, filter?: PortfolioFilter) => void;
}

const translations = {
  en: {
    // Nav
    'nav.home': 'Home',
    'nav.studio': 'Studio',
    'nav.portfolio': 'Portfolio',
    'nav.services': 'Services',
    'nav.aiStudio': 'AI Studio',
    'nav.aiConcepts': 'AI Concepts',
    'nav.pricing': 'Pricing',
    'nav.contact': 'Contact',
    'nav.blog': 'Blog',
    'nav.bookConsultation': 'Book a Consultation',
    'nav.freeConsultation': 'Free Consultation',

    // Hero
    'hero.studio2021': 'Designature Studio Est. 2021',
    'btn.explore': 'Explore Projects',

    // Services
    'serv.title': 'Our Services',
    'serv.heading': 'Everything You Need, Delivered',
    'serv.subtext': 'We bridge the gap between visionary design and technical precision.',
    'btn.example': 'View Example',
    'serv.packageIncludes': 'Package Includes',
    'serv.pageHeroTitle': 'Design Services',
    'serv.pageHeroSub': 'Tailored architectural and interior design solutions for visionary clients.',
    'serv.res.title': 'Residential Design',
    'serv.res.intro': 'Creating intimate, personal sanctuaries that reflect your unique lifestyle.',
    'serv.res.list': 'Concept Development|Space Planning|Material Selection|Furniture Sourcing|Lighting Design',
    'serv.com.title': 'Commercial Design',
    'serv.com.intro': 'Strategic environments designed to enhance brand identity and productivity.',
    'serv.com.list': 'Office Layouts|Retail Interiors|Hospitality Design|Brand Integration|Technical Documentation',
    'serv.ren.title': 'Renovation & Styling',
    'serv.ren.intro': 'Breathe new life into existing spaces through thoughtful intervention.',
    'serv.ren.list': 'Structural Updates|Interior Refresh|Art Curation|Color Consultation|Final Styling',
    'serv.cta.res': 'View Residential',
    'serv.cta.com': 'View Commercial',
    'serv.cta.ren': 'View All Projects',
    'serv.final.title': 'Ready to Start?',
    'serv.final.desc': 'Let\'s transform your vision into an architectural reality.',
    'serv.final.btn': 'Book a Conversation',
    'services.desc': 'Our comprehensive suite of services ensures every aspect of your architectural journey is handled with precision and artistic integrity.',
    'services.downloading': 'Downloading...',
    'services.downloadFailed': 'PDF download failed, opening in new tab',

    // Process
    'proc.title': 'Our Process',
    'proc.subtext': 'A systematic approach to creativity.',
    'proc.step1.title': 'Consultation',
    'proc.step1.desc': 'Initial meeting to understand your vision, goals, and project requirements.',
    'proc.step2.title': 'Concept',
    'proc.step2.desc': 'Developing the core design philosophy and visual direction for the space.',
    'proc.step3.title': 'Design',
    'proc.step3.desc': 'Detailed architectural drawings, 3D visualizations, and material specifications.',
    'proc.step4.title': 'Refinement',
    'proc.step4.desc': 'Collaborative review and fine-tuning of every detail to ensure perfection.',
    'proc.step5.title': 'Execution',
    'proc.step5.desc': 'Project management and coordination to bring the design to life.',
    'proc.step6.title': 'Handover',
    'proc.step6.desc': 'Final walkthrough and delivery of your completed architectural masterpiece.',

    // Projects
    'pro.title': 'Featured Work',
    'pro.heading': 'Come See What We\'ve Created',
    'pro.subtext': 'These spaces started with a conversation. Take a peek at the homes and commercial spaces we have brought to life — each one designed with care.',
    'btn.viewAllProjects': 'View All Projects',

    // Portfolio
    'port.title': 'Our Portfolio',
    'port.heading': 'Curated Projects',
    'port.all': 'All',
    'port.residential': 'Residential',
    'port.commercial': 'Commercial',
    'port.detail.type': 'Project Type',
    'port.detail.area': 'Total Area',
    'port.detail.date': 'Completion',
    'port.detail.location': 'Location',
    'portfolio.title': 'Curated Spaces',
    'portfolio.back': 'BACK TO PORTFOLIO',
    'portfolio.backHome': 'BACK TO HOME',
    'portfolio.next': 'Next Experience',
    'portfolio.exploreMore': 'Explore More',
    'portfolio.return': 'Return to Gallery',
    'portfolio.mainPerspective': 'Main Perspective',
    'portfolio.detailView1': 'Detail View I',
    'portfolio.detailView2': 'Detail View II',
    'portfolio.widePerspective': 'Wide Perspective',
    'portfolio.contextView1': 'Context View I',
    'portfolio.contextView2': 'Context View II',
    'portfolio.closeup1': 'Close-up I',
    'portfolio.closeup2': 'Close-up II',
    'portfolio.closeup3': 'Close-up III',
    'portfolio.atmosphere1': 'Atmosphere I',
    'portfolio.atmosphere2': 'Atmosphere II',
    'portfolio.additionalView': 'Additional View {n}',
    'portfolio.noImage': 'No Image Available',
    'portfolio.view': 'VIEW',

    // Why Choose Us
    'why.title': 'Why Choose Us',
    'why.heading': 'We\'ve got you covered.',
    'why.desc': 'Engineering background meets design vision — every project is technically rigorous, aesthetically considered, and fully managed from concept to completion.',
    'why.label': 'Why Designature',
    'why.p1.title': 'Engineering backbone',
    'why.p1.desc': 'Every concept is structurally sound and code-compliant — not just beautiful.',
    'why.p2.title': 'Global Perspective',
    'why.p2.desc': 'International design standards and trends applied to every local project, wherever you are.',
    'why.p3.title': 'End-to-end process',
    'why.p3.desc': 'First sketch to final brick — we own the complexity so you don\'t have to manage ten contractors.',
    'why.p4.title': 'Remote-First Ready',
    'why.p4.desc': 'Full design service delivered digitally — 3D walkthroughs, live reviews, signed off remotely.',

    // AI Section
    'ai.engine': 'AI Design Studio',
    'ai.heading': 'Design First. Commit Later.',
    'ai.desc': 'Six tools. One page. Free to start.',
    'ai.uploadInsp': 'Upload Inspiration',
    'btn.change': 'Change photo',
    'btn.add': 'Add images',
    'common.optional': 'optional',
    'ai.uploadFloor': 'Upload Room Photo',
    'ai.styleQuiz': 'Style Quiz',
    'ai.aiVision': 'AI Vision',
    'ai.shoppingList': 'Shopping List',
    'ai.roomAudit': 'Room Audit',
    'ai.designBrief': 'Design Brief',
    'ai.culturalAdvisor': 'Cultural Advisor',
    'ai.remaining': 'concepts remaining',
    'ai.unlockAll': 'Sign in to unlock all tools',
    'ai.signInToStart': 'Sign in to start your AI journey',
    'ai.signInQuiz': 'Sign in to discover your design DNA',
    'ai.signInVision': 'Sign in to see your room transformed',
    'ai.signInShopping': 'Sign in to find the real products',
    'ai.noCard': 'No credit card required',
    'ai.toExplore': 'to explore',
    'ai.liveTools': 'live AI tools',
    'ai.discoverDNA': 'Discover your design DNA',
    'ai.transformRoom': 'Transform your room',
    'ai.shopInterior': 'Shop any interior',
    'ai.scoreSpace': 'Score your space',
    'ai.buildBrief': 'Build your brief',
    'ai.blendStyles': 'Blend global styles',
    'ai.nowActive': 'Live',
    'nav.backToHome': 'Back to Home',
    'ai.jumpToTool': 'Jump to any tool above',
    'ai.quizDesc': 'Rate 12 rooms · Get your design DNA · Apply to AI Vision',
    'ai.visionDesc': 'Upload your room · Choose a style · Generate your concept',
    'ai.shopDesc': 'Upload any interior · Find real products · Download PDF',
    'ai.usedAll': "You've used all 3 free generations.",
    'ai.bookConversation': 'Book a Conversation',
    'ai.generateConcept': 'Generate Concept',
    'ai.conceptAppear': 'Your concept will appear here',
    'ai.completeSteps': 'Complete the steps on the left',
    'ai.processingTime': 'This takes about 20–40 seconds',
    'ai.searchFailed': 'Search failed. Please try again.',
    'ai.spatialLogic': 'Spatial Logic',
    'ai.spatialDesc': 'AI analyzes structural flow and optimization.',
    'ai.materialSynthesis': 'Material Synthesis',
    'ai.materialDesc': 'Intelligent texture and color palette generation.',
    'ai.volumeAnalysis': 'Volume Analysis',
    'ai.volumeDesc': '3D massing studies based on 2D inputs.',
    'ai.images': 'images',
    'ai.style.japandi': 'Japandi',
    'ai.style.modern': 'Modern',
    'ai.style.midCentury': 'Mid-Century',
    'ai.style.midcentury': 'Mid-Century',
    'ai.style.bohemian': 'Bohemian',
    'ai.style.rustic': 'Rustic',
    'ai.style.dopamine': 'Dopamine',
    'ai.style.minimalist': 'Minimalist',
    'ai.style.industrial': 'Industrial',
    'ai.style.maximalist': 'Maximalist',
    'ai.style.coastal': 'Coastal',
    'ai.style.artDeco': 'Art Deco',
    'ai.style.artdeco': 'Art Deco',
    'ai.style.transitional': 'Transitional',
    'ai.style.art deco': 'Art Deco',
    'common.processing': 'Processing',
    'ai.shopThisLook': 'Shop This Look',
    'ai.shopThisLookDesc': 'Find the real products from this concept.',
    'ai.findTheseProducts': 'Find These Products',
    'ai.style.biophilic': 'Biophilic',
    'ai.style.scandinavian': 'Scandinavian',
    'ai.style.traditional': 'Traditional',
    'ai.designComplete': 'Design Complete',
    'ai.genVariation': 'Generate variation (uses 1)',
    'btn.reset': 'Reset',
    'ai.originalRoom': 'Original Room',
    'ai.genConcept': 'Generated Concept',
    'ai.genConcepts': 'Generated Concepts',
    'btn.downloadFull': 'Download Full Resolution',
    'btn.downloadAll': 'Download All',
    'ai.quiz.roomOf': 'Room {current} of {total}',
    'ai.quiz.rateHonestly': 'Rate each space honestly',
    'ai.quiz.fromPortfolio': 'From our portfolio',
    'ai.quiz.howFeel': 'How do you feel about this space?',
    'ai.quiz.loveIt': 'Love it',
    'ai.quiz.skip': 'Skip',
    'ai.quiz.notMyStyle': 'Not my style',
    'ai.quiz.tasteSoFar': 'Your taste so far',
    'ai.quiz.designDNA': 'Your design DNA',
    'ai.quiz.basedOnRatings': 'Based on your ratings',
    'ai.quiz.applyStyle': 'Apply {style} style to AI Vision',
    'ai.quiz.retake': 'Retake quiz',
    'ai.quiz.stylePreselected': 'Your top style ({style}) will be pre-selected in AI Vision so your first concept matches your taste.',
    'ai.shop.signIn': 'Sign in to use the Shopping List',
    'ai.shop.shopIn': 'Shop in:',
    'ai.shop.anyInterior': 'Shop Any Interior',
    'ai.shop.anyInteriorDesc': 'Upload any interior photo and we will find the real products in it.',
    'ai.shop.imageReady': 'Image ready',
    'ai.shop.findProducts': 'Find Products',
    'ai.shop.change': 'Change',
    'ai.shop.uploadPhoto': 'Upload an Interior Photo',
    'ai.shop.newConcept': 'New Concept Generated',
    'ai.shop.newConceptDesc': 'Re-search to find products matching this new concept.',
    'ai.shop.reSearch': 'Re-Search Products',
    'ai.shop.identifying': 'Identifying furniture & searching shops...',
    'ai.shop.processingTime': 'About 15-20 seconds',
    'ai.shop.itemsIdentified': '{count} items identified:',
    'ai.shop.items': '{count} items',
    'ai.shop.noProducts': 'No products found. Try a different concept.',
    'ai.shop.noProductsForItem': 'No products found for this item.',
    'ai.shop.resultsVia': "Results via Serper · Click any product to view on retailer's site · Prices may vary",
    'ai.shop.downloadPDF': 'Download PDF',
    'ai.loveWhatSee': 'Love what you see?',
    'ai.readyMakeReal': 'Ready to make this real?',
    'ai.firstConversation': 'First conversation is on us — no commitment',
    'ai.design': 'Design',
    'ai.studio': 'Studio',
    'ai.studio.desc': 'Your personal interior design assistant. Experiment with styles, visualize transformations, and find real products.',
    'ai.quiz.title': 'Style Quiz',
    'ai.quiz.desc': 'Discover your design DNA in 60 seconds.',
    'ai.vision.title': 'AI Vision',
    'ai.vision.desc': 'See your room transformed into any style instantly.',
    'ai.shop.title': 'Shopping List',
    'ai.shop.desc': 'Find real furniture from your favorite concepts.',
    'ai.signInFailed': 'Sign in failed. Please try again.',
    'ai.noGenerationsLeft': 'No generations left.',
    'ai.generationFailed': 'Generation failed. Please try again.',
    'ai.apiKeyError': 'API key permission error. Please check your key settings.',
    'ai.quotaExceeded': 'Quota exceeded. Please wait a moment and try again.',
    'ai.uploadRoomImage': 'Please upload a room image first.',
    'ai.uploadInspRoom': 'Please upload at least 1 inspiration image and your room photo',
    'btn.tryAi': 'Start Free — No Card Needed',
    'ai.quiz.applyStyleToRoom': 'Apply {style} to my room',

    // Multimodal Search (Design First)
    'ai.designFirst.label': 'AI-Powered Design Studio',
    'ai.designFirst.title1': 'Design First.',
    'ai.designFirst.title2': 'Commit Later.',
    'ai.designFirst.desc': 'Use our AI tools to explore possibilities before making any big decisions.',
    'ai.designFirst.tool1': 'Style Quiz — discover your design DNA',
    'ai.designFirst.tool2': 'AI Vision — see your room transformed',
    'ai.designFirst.tool3': 'Shopping List — find the real products',
    'ai.designFirst.tool4': 'Room Audit, Design Brief & more',
    'ai.designFirst.footerDesc': 'Then book a consultation with Anahit — and come in knowing exactly what you want.',
    'ai.designFirst.freeConcepts': 'Free concepts',
    'ai.designFirst.designStyles': 'Design styles',
    'ai.designFirst.genTime': 'Generation time',
    'ai.designFirst.toExplore': 'To explore',
    'ai.designFirst.before': 'Before',

    // Testimonials
    'test.title': 'Client Stories',
    'test.heading': 'Voices of Designature',
    'test.subtext': 'What our clients say about their journey with us.',
    'testimonials.label': 'Testimonials',
    'testimonials.title': 'What Our Clients Say',
    'testimonials.desc': 'We take pride in building lasting relationships through exceptional design and dedicated service.',
    'testimonials.feedback': 'Share your feedback with us',

    // Blog
    'blog.title': 'Insights',
    'blog.heading': 'Design Philosophy',
    'blog.viewAll': 'View All Articles',
    'btn.allInsights': 'All Insights',

    // CTA Banner
    'cta.banner.title': 'Ready when you are.',
    'cta.banner.subtext': 'You\'ve seen the AI concepts. Now let\'s build the real thing.',
    'cta.banner.btn': 'Book a Conversation',

    // Footer
    'footer.studio': 'Studio',
    'footer.usefulLinks': 'Useful Links',
    'footer.contacts': 'Contacts',
    'footer.newsletterHeader': 'Stay Inspired',
    'footer.emailLabel': 'Your Email Address',
    'footer.subscribe': 'Subscribe',
    'footer.submitting': 'Submitting...',
    'footer.newsletterSub': 'Join our newsletter for exclusive design insights and project updates.',
    'footer.about': 'About Us',
    'footer.terms': 'Terms of Service',
    'footer.privacy': 'Privacy Policy',
    'footer.usOffice': 'US Office',
    'footer.amOffice': 'Armenia Office',
    'footer.rights': '© 2024 Designature Studio. All Rights Reserved.',
    'footer.successTitle': 'Welcome to the Studio',
    'footer.successDesc': 'You\'ve successfully subscribed to our newsletter. Expect curated design inspiration in your inbox soon.',
    'footer.close': 'Close',
    'footer.follow': 'Follow Us',
    'footer.contact': 'Contact',
    'footer.newsletter': 'Newsletter',
    'footer.newsletterDesc': 'Subscribe to receive our latest design insights.',
    'footer.success': 'Subscribed!',

    // Header Buttons
    'btn.bookCall': 'Book a Conversation',
    'btn.firstConvo': 'First Conversation is on Us',

    // Studio Page
    'studio.heroTitle': 'The Studio',
    'studio.heroSub': 'Where architectural precision meets artistic soul. Founded in 2021, we redefine the boundaries of modern living.',
    'studio.hero.title': 'The Studio',
    'studio.hero.desc': 'A collective of architects and designers dedicated to the art of living well.',
    'studio.aboutTitle': 'Our Story',
    'studio.aboutHeading': 'Crafting Spaces with Purpose',
    'studio.aboutDesc1': 'Designature Studio was born from a desire to bridge the gap between technical engineering and pure aesthetic expression.',
    'studio.aboutDesc2': 'We believe that a space should do more than just function—it should tell a story, evoke emotion, and stand as a testament to the vision of its inhabitants.',
    'studio.founded': 'Founded',
    'studio.projects': 'Projects Delivered',
    'studio.founderTitle': 'The Visionary',
    'studio.founderRole': 'Founder & Lead Designer',
    'studio.founder.label': 'Founder & Lead Architect',
    'studio.founder.role': 'Architect · Interior Designer',
    'studio.founder.quote': 'Design is not just what it looks like and feels like. Design is how it works.',
    'studio.founder.bio': 'With over a decade of experience across Europe and the Middle East, Anahit brings a global perspective to local craftsmanship.',
    'studio.founderQuote': 'Design is not just what it looks like; it\'s how it makes you feel when you walk through the door.',
    'studio.founderBio': 'With over a decade of experience in international architectural firms, Anahit Ghasabyan founded Designature to bring a new level of personalized, high-end design to Armenia and beyond.',
    'studio.story.title': 'Our Story & Philosophy',
    'studio.story.p1': 'Founded in 2021, Designature was born from a simple belief: that the spaces we inhabit profoundly shape the quality of our lives.',
    'studio.story.p2': 'We don\'t believe in "styles" as fixed rules. We believe in signatures — the unique intersection of a client\'s personality and the architectural potential of a site.',
    'studio.story.p3': 'We design for the human being first — listening before drawing, understanding before deciding. Every material is chosen for what it truly is, not what a trend demands of it. The result is spaces that feel deeply considered today, and will remain that way a decade from now.',
    'studio.contactHeading': 'Let\'s Connect',
    'studio.contactSub': 'Whether you have a fully formed vision or just the seed of an idea, we\'re here to help you grow it.',
    'studio.contact.title': 'Get in touch',
    'studio.contact.hero': 'Let\'s build something remarkable',
    'studio.contact.desc': 'Have a project in mind? We\'d love to hear about it. Our team is ready to help you bring your vision to life.',
    'studio.contact.email': 'Email',
    'studio.contact.phone': 'Phone',
    'studio.contact.location': 'Studio',
    'studio.contact.location.desc': 'Yerevan, Armenia and Worldwide',
    'studio.contact.form.title': 'Send us a message',
    'studio.contact.form.name': 'Your full name',
    'studio.contact.form.email': 'your@email.com',
    'studio.contact.form.subject': 'Living room redesign · 120m²',
    'studio.contact.form.message': 'Tell us about your project, timeline, vision…',
    'studio.contact.form.success': 'Message sent successfully!',
    'studio.contact.form.error': 'Failed to send message. Please try again.',
    'studio.emailUs': 'Email Us',
    'studio.callUs': 'Call Us',
    'studio.visitUs': 'Visit Us',
    'studio.formName': 'Full Name',
    'studio.formEmail': 'Email Address',
    'studio.formSubject': 'Subject',
    'studio.formMessage': 'Your Message',
    'studio.formSend': 'Send Message',
    'studio.formSending': 'Sending...',
    'studio.formSuccess': 'Message Sent Successfully',
    'studio.formError': 'Error Sending Message',

    // AI Vision Page
    'ai.vision.hero': 'AI Vision',
    'ai.vision.heroDesc': 'We don\'t use AI to replace the architect. We use it to augment the human imagination and eliminate technical friction.',
    'ai.vision.back': 'BACK TO HOME',
    'ai.vision.point1.title': 'Hyper-Personalization',
    'ai.vision.point1.desc': 'AI that learns your subconscious aesthetic preferences to suggest spaces you didn\'t know you needed.',
    'ai.vision.point2.title': 'Real-time Iteration',
    'ai.vision.point2.desc': 'Instantly visualize structural changes, material swaps, and lighting scenarios during our design sessions.',
    'ai.vision.point3.title': 'Predictive Engineering',
    'ai.vision.point3.desc': 'Advanced algorithms that predict structural longevity and energy efficiency before the first brick is laid.',
    'ai.vision.point4.title': 'Ethical Automation',
    'ai.vision.point4.desc': 'Using technology to handle the mundane, freeing our architects to focus purely on the soul and art of your project.',
    'ai.vision.quote': 'The algorithm of beauty is human.',
    'ai.vision.cta': 'Learn about our philosophy',

    // General Buttons
    'btn.generate': 'Generate Concept',
    'btn.download': 'Download',
    'btn.book': 'Book a Conversation',
    'btn.back': 'Back',
    'btn.next': 'Next',
    'btn.close': 'Close',
    'btn.send': 'Send',
  },
  am: {
    // Nav
    'nav.studio': 'Ստուդիա',
    'nav.portfolio': 'Պորտֆոլիո',
    'nav.services': 'Ծառայություններ',
    'nav.aiConcepts': 'AI Կոնցեպտներ',
    'nav.contact': 'Կապ',
    'nav.blog': 'Բլոգ',

    // Hero
    'hero.studio2021': 'Ճարտարապետական Ստուդիա / Հիմն. 2021',
    'btn.explore': 'Տեսնել Նախագծերը',

    // Services
    'serv.title': 'Մեր Փորձը',
    'serv.heading': 'Ճարտարապետական Լուծումներ',
    'serv.subtext': 'Մենք կամրջում ենք տեսլականային դիզայնը և տեխնիկական ճշգրտությունը:',
    'btn.example': 'Տեսնել Օրինակը',
    'serv.packageIncludes': 'Փաթեթը Ներառում է',
    'serv.pageHeroTitle': 'Դիզայն Ծառայություններ',
    'serv.pageHeroSub': 'Ճարտարապետական և ինտերիեր դիզայնի անհատական լուծումներ տեսլական ունեցող հաճախորդների համար:',
    'serv.res.title': 'Բնակելի Դիզայն',
    'serv.res.intro': 'Ստեղծելով մտերիմ, անհատական տարածքներ, որոնք արտացոլում են Ձեր յուրահատուկ կենսակերպը:',
    'serv.res.list': 'Կոնցեպտի Մշակում|Տարածքի Պլանավորում|Նյութերի Ընտրություն|Կահույքի Հայթայթում|Լուսավորության Դիզայն',
    'serv.com.title': 'Կոմերցիոն Դիզայն',
    'serv.com.intro': 'Ռազմավարական միջավայրեր՝ նախատեսված բրենդի ինքնությունը և արտադրողականությունը բարձրացնելու համար:',
    'serv.com.list': 'Գրասենյակային Պլանավորում|Մանրածախ Ինտերիեր|Հյուրընկալության Դիզայն|Բրենդի Ինտեգրում|Տեխնիկական Փաստաթղթեր',
    'serv.ren.title': 'Վերանորոգում և Սթայլինգ',
    'serv.ren.intro': 'Նոր շունչ հաղորդել գոյություն ունեցող տարածքներին մտածված միջամտության միջոցով:',
    'serv.ren.list': 'Կառուցվածքային Թարմացում|Ինտերիերի Թարմացում|Արվեստի Համադրում|Գունային Խորհրդատվություն|Վերջնական Սթայլինգ',
    'serv.cta.res': 'Տեսնել Բնակելին',
    'serv.cta.com': 'Տեսնել Կոմերցիոնը',
    'serv.cta.ren': 'Տեսնել Բոլորը',
    'serv.final.title': 'Պատրա՞ստ եք Սկսել',
    'serv.final.desc': 'Եկեք վերափոխենք Ձեր տեսլականը ճարտարապետական իրականության:',
    'serv.final.btn': 'Ամրագրել զրույց',

    // Process
    'proc.title': 'Մեր Գործընթացը',
    'proc.subtext': 'Համակարգված մոտեցում ստեղծագործականությանը:',
    'proc.step1.title': 'Խորհրդատվություն',
    'proc.step1.desc': 'Նախնական հանդիպում՝ Ձեր տեսլականը, նպատակները և նախագծի պահանջները հասկանալու համար:',
    'proc.step2.title': 'Կոնցեպտ',
    'proc.step2.desc': 'Տարածքի հիմնական դիզայնի փիլիսոփայության և տեսողական ուղղության մշակում:',
    'proc.step3.title': 'Դիզայն',
    'proc.step3.desc': 'Մանրամասն ճարտարապետական գծագրեր, 3D վիզուալիզացիա և նյութերի սպեցիֆիկացիա:',
    'proc.step4.title': 'Կատարելագործում',
    'proc.step4.desc': 'Համատեղ վերանայում և յուրաքանչյուր մանրուքի հղկում՝ կատարելությունն ապահովելու համար:',
    'proc.step5.title': 'Իրականացում',
    'proc.step5.desc': 'Նախագծի կառավարում և համակարգում՝ դիզայնը կյանքի կոչելու համար:',
    'proc.step6.title': 'Հանձնում',
    'proc.step6.desc': 'Վերջնական ստուգում և Ձեր պատրաստի ճարտարապետական գլուխգործոցի հանձնում:',

    // Projects
    'pro.title': 'Ընտրված Աշխատանքներ',
    'pro.heading': 'Հեղինակային Նախագծեր',
    'pro.subtext': 'Մեր վերջին ճարտարապետական և ինտերիեր ձեռքբերումների ընտրանին:',
    'btn.viewAllProjects': 'Տեսնել Բոլոր Նախագծերը',

    // Portfolio
    'port.title': 'Մեր Պորտֆոլիոն',
    'port.heading': 'Ընտրված Նախագծեր',
    'port.all': 'Բոլորը',
    'port.residential': 'Բնակելի',
    'port.commercial': 'Կոմերցիոն',
    'port.detail.type': 'Նախագծի Տեսակը',
    'port.detail.area': 'Ընդհանուր Մակերես',
    'port.detail.date': 'Ավարտ',
    'port.detail.location': 'Վայրը',

    // Why Choose Us
    'why.title': 'Ինչու ynt8el Mez',
    'why.heading': 'Ստուդիայի Ստանդարտը',
    'why.desc': 'Մենք համատեղում ենք ինժեներական ճշգրտությունը գեղարվեստական տեսլականի հետ:',
    'why.p1.title': 'Ինժեներական Ճշգրտություն',
    'why.p1.desc': 'Յուրաքանչյուր դիզայն հիմնված է խիստ տեխնիկական ստանդարտների և կառուցվածքային ամրության վրա:',
    'why.p2.title': 'Գլոբալ Հեռանկար',
    'why.p2.desc': 'Միջազգային դիզայնի տենդենցների և ստանդարտների ներդրում յուրաքանչյուր տեղական նախագծում:',
    'why.p3.title': 'Անխափան Գործընթաց',
    'why.p3.desc': 'Առաջին էսքիզից մինչև վերջին աղյուսը, մենք կառավարում ենք բարդությունը Ձեր փոխարեն:',
    'why.p4.title': 'Հեռավար Աշխատանք',
    'why.p4.desc': 'Ժամանակակից թվային գործիքները թույլ են տալիս մեզ արդյունավետ համագործակցել հաճախորդների հետ ամբողջ աշխարհում:',

    // AI Section
    'ai.engine': 'AI Design Studio',
    'ai.heading': 'Դիզայնը՝ առաջինը: Պարտավորությունները՝ հետո:',
    'ai.desc': 'Վեց գործիք: Մեկ էջ: Անվճար սկիզբ:',
    'ai.uploadInsp': 'Վերբեռնել Ներշնչանք',
    'btn.change': 'Change photo',
    'btn.add': 'Add images',
    'common.optional': 'optional',
    'ai.uploadFloor': 'Upload Room Photo',
    'ai.styleQuiz': 'Ոճի Քվիզ',
    'ai.aiVision': 'AI Տեսլական',
    'ai.shoppingList': 'Գնումների Ցուցակ',
    'ai.roomAudit': 'Սենյակի Աուդիտ',
    'ai.designBrief': 'Դիզայն Բրիֆ',
    'ai.culturalAdvisor': 'Մշակութային Խորհրդատու',
    'ai.remaining': 'կոնցեպտ մնաց',
    'ai.unlockAll': 'Մուτq',
    'ai.signInToStart': 'Մուτq',
    'ai.signInQuiz': 'Մուτq',
    'ai.signInVision': 'Մուτq',
    'ai.signInShopping': 'Մուτq',
    'ai.noCard': 'Քարտ չի պահանջվում',
    'ai.toExplore': 'բացահայտելու',
    'ai.liveTools': 'ակտիվ AI գործիքներ',
    'ai.discoverDNA': 'Բացահայտեք Ձեր դիզայնի ԴՆԹ-ն',
    'ai.transformRoom': 'Ձևափոխեք Ձեր սենյակը',
    'ai.shopInterior': 'Գնեք ցանկացած ինտերիեր',
    'ai.scoreSpace': 'Գնահատեք Ձեր տարածքը',
    'ai.buildBrief': 'Ստեղծեք Ձեր բրիֆը',
    'ai.blendStyles': 'Համադրեք համաշխարհային ոճերը',
    'ai.nowActive': 'Այժմ ակտիվ է',
    'ai.quizDesc': 'Գնահատեք 12 սենյակ · Ստացեք Ձեր ԴՆԹ-ն · Կիրառեք AI Vision-ում',
    'ai.visionDesc': 'Բեռնեք սենյակը · Ընտրեք ոճը · Ստեղծեք կոնցեպտը',
    'ai.shopDesc': 'Բեռնեք ցանկացած ինտերիեր · Գտեք ապրանքները · Ներբեռնեք PDF',
    'ai.usedAll': 'Դուք օգտագործել եք բոլոր 3 անվճար գեներացիաները:',
    'ai.bookConversation': 'Ամրագրել զրույց',
    'ai.generateConcept': 'Ստեղծել Կոնցեպտ',
    'ai.conceptAppear': 'Ձեր կոնցեպտը կհայտնվի այստեղ',
    'ai.completeSteps': 'Լրացրեք ձախ կողմի քայլերը',
    'ai.processingTime': '20-40 վայրկյան',
    'ai.searchFailed': 'Որոնումը ձախողվեց:',
    'ai.spatialLogic': 'Տարածական Տրամաբանություն',
    'ai.spatialDesc': 'AI-ն վերլուծում է կառուցվածքային հոսքը:',
    'ai.materialSynthesis': 'Նյութերի Սինթեզ',
    'ai.materialDesc': 'Հյուսվածքների և գունային գամմաների սինթեզ:',
    'ai.volumeAnalysis': 'Ծավալային Վերլուծություն',
    'ai.volumeDesc': '3D ծավալային ուսումնասիրություններ:',
    'ai.images': 'նկար',
    'ai.style.japandi': 'Japandi',
    'ai.style.artdeco': 'Art Deco',
    'ai.style.transitional': 'Transitional',
    'ai.style.art deco': 'Art Deco',
    'common.processing': 'Processing',
    'ai.shopThisLook': 'Shop This Look',
    'ai.shopThisLookDesc': 'Find the real products from this concept.',
    'ai.findTheseProducts': 'Find These Products',
    'ai.style.modern': 'Modern',
    'ai.style.midCentury': 'Mid-Century',
    'ai.style.midcentury': 'Mid-Century',
    'ai.style.scandinavian': 'Scandinavian',
    'ai.style.traditional': 'Traditional',
    'ai.style.bohemian': 'Bohemian',
    'ai.style.rustic': 'Rustic',
    'ai.style.dopamine': 'Dopamine',
    'ai.style.minimalist': 'Minimalist',
    'ai.style.industrial': 'Industrial',
    'ai.style.maximalist': 'Maximalist',
    'ai.style.coastal': 'Coastal',
    'ai.style.artDeco': 'Art Deco',
    'ai.style.biophilic': 'Biophilic',
    'btn.tryAgain': 'Նորից Փորձել',
    'ai.designComplete': 'Դիզայնը Պատրաստ է',
    'ai.genVariation': 'Ստեղծել Տարբերակ',
    'btn.reset': 'Մաքրել',
    'ai.originalRoom': 'Բնօրինակ',
    'ai.genConcept': 'Գեներացված',
    'ai.genConcepts': 'Գեներացված Կոնցեպտներ',
    'ai.quiz.roomOf': 'Սենյակ {current} - {total}',
    'ai.quiz.rateHonestly': 'Գնահատեք յուրաքանչյուր տարածքը',
    'ai.quiz.fromPortfolio': 'Մեր պորտֆոլիոյից',
    'ai.quiz.howFeel': 'Ինչպե՞ս եք զգում այս տարածքում:',
    'ai.quiz.loveIt': 'Սիրում եմ',
    'ai.quiz.skip': 'Բաց թողնել',
    'ai.quiz.notMyStyle': 'Իմ ոճը չէ',
    'ai.quiz.tasteSoFar': 'Ձեր ճաշակը',
    'ai.quiz.designDNA': 'Ձեր դիզայնի ԴՆԹ-ն',
    'ai.quiz.basedOnRatings': 'Հիմնված Ձեր գնահատականների վրա',
    'ai.quiz.applyStyle': 'Կիրառել {style} ոճը AI Vision-ում',
    'ai.quiz.retake': 'Կրկնել քվիզը',
    'ai.quiz.stylePreselected': 'Ձեր լավագույն ոճը ({style}) կընտրվի AI Vision-ում:',
    'ai.shop.signIn': 'Մուտք գործեք Shopping List-ի համար',
    'ai.shop.shopIn': 'Գնումներ կատարել',
    'ai.shop.anyInterior': 'Գնել ցանկացած ինտերիեր',
    'ai.shop.anyInteriorDesc': 'Բեռնեք ցանկացած լուսանկար',
    'ai.shop.imageReady': 'Պատրաստ է',
    'ai.shop.findProducts': 'Գտնել',
    'ai.shop.change': 'Փոխել',
    'ai.shop.uploadPhoto': 'Բեռնել լուսանկար',
    'ai.shop.newConcept': 'Նոր Կոնցեպտ',
    'ai.shop.newConceptDesc': 'Որոնել նոր կոնցեպտի համար',
    'ai.shop.reSearch': 'Որոնել Կրկին',
    'ai.shop.identifying': 'Որոնվում է...',
    'ai.shop.processingTime': '15-20 վայրկյան',
    'ai.shop.itemsIdentified': '{count} items',
    'ai.shop.items': '{count} items',
    'ai.shop.noProducts': 'Ապրանքներ չեն գտնվել',
    'ai.shop.noProductsForItem': 'Ապրանքներ չեն գտնվել',
    'ai.shop.resultsVia': 'Արդյունքները Google-ից են:',
    'ai.shop.downloadPDF': 'PDF Ներբեռնել',
    'btn.downloadFull': 'Ներբեռնել',
    'btn.downloadAll': 'Բոլորը',
    'ai.loveWhatSee': 'Հավանո՞ւմ եք',
    'ai.readyMakeReal': 'Պատրա՞ստ եք',
    'ai.firstConversation': 'Առաջին խոսակցությունն անվճար է',
    'ai.design': 'Դիզայն',
    'ai.studio': 'Ստուդիա',
    'ai.signInFailed': 'Մուտքը ձախողվեց:',
    'ai.noGenerationsLeft': 'Գեներացիաները սպառվել են:',
    'ai.generationFailed': 'Գեներացումը ձախողվեց:',
    'ai.apiKeyError': 'API բանալու սխալ:',
    'ai.quotaExceeded': 'Քվոտան սպառված է:',
    'ai.uploadRoomImage': 'Բեռնեք լուսանկարը:',
    'ai.uploadInspRoom': 'Խնդրում ենք վերբեռնել առնվազն 1 ոգեշնչման լուսանկար և ձեր սենյակի լուսանկարը',
    'btn.tryAi': 'Սկսել Անվճար',

    // Testimonials
    'test.title': 'Հաճախորդների Պատմություններ',
    'test.heading': 'Ինչ են Խոսում Մեր Մասին',
    'test.subtext': 'Ինչ են ասում մեր հաճախորդները մեզ հետ իրենց անցած ուղու մասին:',

    // Blog
    'blog.title': 'Մտքեր',
    'blog.heading': 'Դիզայնի Փիլիսոփայություն',
    'btn.allInsights': 'Բոլոր Հոդվածները',

    // CTA Banner
    'cta.banner.title': 'Ձեր Տեսլականը, Մեր Ստորագրությունը:',
    'cta.banner.subtext': 'Միացեք տեսլական ունեցող տանտերերի և կառուցապատողների շարքին, ովքեր ընտրում են Դիզայնեյչրը իրենց ամենահավակնոտ նախագծերի համար:',
    'cta.banner.btn': 'Ամրագրել զրույց մեր կողմից',

    // Footer
    'footer.studio': 'Ստուդիա',
    'footer.usefulLinks': 'Օգտակար Հղումներ',
    'footer.contacts': 'Կապ',
    'footer.newsletterHeader': 'Մնացեք Ներշնչված',
    'footer.emailLabel': 'Ձեր Էլ. Փոստը',
    'footer.subscribe': 'Բաժանորդագրվել',
    'footer.submitting': 'Ուղարկվում է...',
    'footer.newsletterSub': 'Միացեք մեր լրատվականին՝ դիզայնի բացառիկ մտքերի և նախագծերի թարմացումների համար:',
    'footer.about': 'Մեր Մասին',
    'footer.terms': 'Օգտագործման Պայմաններ',
    'footer.privacy': 'Գաղտնիության Քաղաքականություն',
    'footer.usOffice': 'ԱՄՆ Գրասենյակ',
    'footer.amOffice': 'Հայաստանի Գրասենյակ',
    'footer.rights': '© 2024 Դիզայնեյչր Ստուդիա. Բոլոր իրավունքները պաշտպանված են:',
    'footer.successTitle': 'Բարի Գալուստ Ստուդիա',
    'footer.successDesc': 'Դուք հաջողությամբ բաժանորդագրվել եք մեր լրատվականին: Շուտով Ձեր էլ. փոստին կստանաք ընտրված դիզայնի ներշնչանքներ:',
    'footer.close': 'Փակել',

    // Header Buttons
    'btn.bookCall': 'Ամրագրել զրույց',
    'btn.firstConvo': 'Առաջին զրույցը մեր կողմից է',

    // Studio Page
    'studio.heroTitle': 'Ստուդիա',
    'studio.heroSub': 'Այնտեղ, որտեղ ճարտարապետական ճշգրտությունը հանդիպում է գեղարվեստական հոգուն: Հիմնադրված 2021-ին, մենք վերասահմանում ենք ժամանակակից կյանքի սահմանները:',
    'studio.aboutTitle': 'Մեր Պատմությունը',
    'studio.aboutHeading': 'Ստեղծելով Տարածքներ Նպատակով',
    'studio.aboutDesc1': 'Դիզայնեյչր Ստուդիան ծնվել է տեխնիկական ինժեներիայի և մաքուր էսթետիկ արտահայտման միջև կամուրջ ստեղծելու ցանկությունից:',
    'studio.aboutDesc2': 'Մենք հավատում ենք, որ տարածքը պետք է ավելին անի, քան պարզապես գործի. այն պետք է պատմի պատմություն, արթնացնի էմոցիաներ և լինի իր բնակիչների տեսլականի վկայությունը:',
    'studio.founded': 'Հիմնադրվել է',
    'studio.projects': 'Ավարտված Նախագծեր',
    'studio.founderTitle': 'Տեսլականը',
    'studio.founderRole': 'Հիմնադիր և Գլխավոր Դիզայներ',
    'studio.founderQuote': 'Դիզայնը միայն այն չէ, թե ինչ տեսք ունի. այն այն է, թե ինչպես եք Ձեզ զգում, երբ ներս եք մտնում դռնից:',
    'studio.founderBio': 'Միջազգային ճարտարապետական ընկերություններում ավելի քան տասը տարվա փորձով Անահիտ Ղասաբյանը հիմնադրել է Դիզայնեյչրը՝ Հայաստանում և դրանից դուրս անհատականացված, բարձրակարգ դիզայնի նոր մակարդակ բերելու համար:',
    'studio.contactHeading': 'Կապվեք Մեզ Հետ',
    'studio.contactSub': 'Անկախ նրանից, թե Դուք ունեք ամբողջական տեսլական, թե պարզապես գաղափարի սաղմ, մենք այստեղ ենք՝ օգնելու Ձեզ աճեցնել այն:',
    'studio.emailUs': 'Էլ. Փոստ',
    'studio.callUs': 'Զանգահարեք Մեզ',
    'studio.visitUs': 'Այցելեք Մեզ',
    'studio.formName': 'Անուն Ազգանուն',
    'studio.formEmail': 'Էլ. Փոստի Հասցե',
    'studio.formSubject': 'Թեմա',
    'studio.formMessage': 'Ձեր Հաղորդագրությունը',
    'studio.formSend': 'Ուղարկել',
    'studio.formSending': 'Ուղարկվում է...',
    'studio.formSuccess': 'Հաղորդագրությունը Հաջողությամբ Ուղարկվեց',
    'studio.formError': 'Սխալ հաղորդագրությունն ուղարկելիս',

    // AI Vision Page
    'ai.vision.hero': 'AI ՏԵՍԼԱԿԱՆ',
    'ai.vision.heroDesc': 'Մենք չենք օգտագործում AI-ն ճարտարապետին փոխարինելու համար: Մենք օգտագործում ենք այն մարդկային երևակայությունն ընդլայնելու և տեխնիկական խոչընդոտները վերացնելու համար:',
    'ai.vision.back': 'ՎԵՐԱԴԱՌՆԱԼ ԳԼԽԱՎՈՐ',
    'ai.vision.point1.title': 'Գեր-անհատականացում',
    'ai.vision.point1.desc': 'AI, որը սովորում է Ձեր ենթագիտակցական էսթետիկ նախասիրությունները՝ առաջարկելով տարածքներ, որոնց կարիքը Դուք չգիտեիք, որ ունեք:',
    'ai.vision.point2.title': 'Իրական ժամանակի փոփոխություններ',
    'ai.vision.point2.desc': 'Ակնթարթորեն վիզուալիզացրեք կառուցվածքային փոփոխությունները, նյութերի փոխարինումը և լուսավորության սցենարները մեր դիզայն-սեսիաների ժամանակ:',
    'ai.vision.point3.title': 'Կանխատեսող ինժեներիա',
    'ai.vision.point3.desc': 'Առաջադեմ ալգորիթմներ, որոնք կանխատեսում են կառուցվածքային երկարակեցությունը և էներգաարդյունավետությունը նախքան առաջին աղյուսը դնելը:',
    'ai.vision.point4.title': 'Էթիկական ավտոմատացում',
    'ai.vision.point4.desc': 'Տեխնոլոգիաների կիրառում առօրյա գործերը հոգալու համար՝ ազատելով մեր ճարտարապետներին կենտրոնանալու բացառապետ Ձեր նախագծի հոգու և արվեստի վրա:',
    'ai.vision.quote': 'Գեղեցկության ալգորիթմը մարդն է:',
    'ai.vision.cta': 'Ծանոթացեք մեր փիլիսոփայությանը',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');
  const [currentPage, setCurrentPage] = useState<Page>(() => getInitialPage());
  const [selectedProjectId, setSelectedProjectId] = useState<string | null>(null);
  const [portfolioFilter, setPortfolioFilter] = useState<PortfolioFilter>('All');

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [currentPage]);

  useEffect(() => {
    localStorage.setItem(STORAGE_KEYS.currentPage, currentPage);
  }, [currentPage]);

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  const navigateTo = (page: Page, projectId?: string, filter?: PortfolioFilter) => {
    if (projectId) setSelectedProjectId(projectId);
    if (filter) setPortfolioFilter(filter);
    setCurrentPage(page);
  };

  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage, 
      t, 
      currentPage, 
      selectedProjectId, 
      setSelectedProjectId,
      portfolioFilter,
      setPortfolioFilter,
      navigateTo 
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
