
import React, { createContext, useContext, useState, useRef, ReactNode, useEffect } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';

// Armenian removed 2026-08-27 (owner call). Type stays as a single-member union
// so future contributors know the toggle deliberately doesn't exist — this is
// not an oversight. See memory: feedback_no_armenian_translations.md.
export type Language = 'en';
export type Page = 'home' | 'portfolio' | 'project-detail' | 'services' | 'studio' | 'deliverables' | 'ai-concepts' | 'ai-vision' | 'pricing' | 'faq' | 'journal' | 'journal-detail' | 'journal-category' | 'terms' | 'privacy' | 'refund' | 'consultation' | 'booking-confirmed' | 'booking-failed';
export type PortfolioFilter = 'All' | 'Residential' | 'Commercial';

// URL ⇄ page-state mapping. URL is the source of truth; localStorage persistence
// has been removed since the browser address bar now records which page you're on.
function pathToPageState(pathname: string): { page: Page; projectId: string | null } {
  if (pathname === '/' || pathname === '') return { page: 'home', projectId: null };
  if (pathname === '/portfolio') return { page: 'portfolio', projectId: null };
  const projectMatch = pathname.match(/^\/portfolio\/([^/]+)\/?$/);
  if (projectMatch) return { page: 'project-detail', projectId: decodeURIComponent(projectMatch[1]) };
  if (pathname === '/services') return { page: 'services', projectId: null };
  if (pathname === '/studio') return { page: 'studio', projectId: null };
  if (pathname === '/deliverables') return { page: 'deliverables', projectId: null };
  if (pathname === '/ai-concepts') return { page: 'ai-concepts', projectId: null };
  if (pathname === '/ai-vision') return { page: 'ai-vision', projectId: null };
  if (pathname === '/pricing') return { page: 'pricing', projectId: null };
  if (pathname === '/faq') return { page: 'faq', projectId: null };
  if (pathname === '/journal') return { page: 'journal', projectId: null };
  if (/^\/journal\/category\/[^/]+\/?$/.test(pathname)) return { page: 'journal-category', projectId: null };
  if (/^\/journal\/[^/]+\/?$/.test(pathname)) return { page: 'journal-detail', projectId: null };
  if (pathname === '/terms') return { page: 'terms', projectId: null };
  if (pathname === '/privacy') return { page: 'privacy', projectId: null };
  if (pathname === '/refund') return { page: 'refund', projectId: null };
  if (pathname === '/consultation') return { page: 'consultation', projectId: null };
  if (pathname === '/booking/confirmed') return { page: 'booking-confirmed', projectId: null };
  if (pathname === '/booking/failed') return { page: 'booking-failed', projectId: null };
  return { page: 'home', projectId: null };
}

function pageToPath(page: Page, projectId?: string | null, filter?: PortfolioFilter): string {
  switch (page) {
    case 'home':
      return '/';
    case 'portfolio':
      return filter && filter !== 'All' ? `/portfolio?filter=${filter}` : '/portfolio';
    case 'project-detail':
      return projectId ? `/portfolio/${encodeURIComponent(projectId)}` : '/portfolio';
    case 'services':
      return '/services';
    case 'studio':
      return '/studio';
    case 'deliverables':
      return '/deliverables';
    case 'ai-concepts':
      return '/ai-concepts';
    case 'ai-vision':
      return '/ai-vision';
    case 'pricing':
      return '/pricing';
    case 'faq':
      return '/faq';
    case 'journal':
      return '/journal';
    case 'journal-detail':
      return projectId ? `/journal/${encodeURIComponent(projectId)}` : '/journal';
    case 'journal-category':
      return projectId ? `/journal/category/${encodeURIComponent(projectId)}` : '/journal';
    case 'terms':
      return '/terms';
    case 'privacy':
      return '/privacy';
    case 'refund':
      return '/refund';
    case 'consultation':
      return '/consultation';
    case 'booking-confirmed':
      return '/booking/confirmed';
    case 'booking-failed':
      return '/booking/failed';
  }
}

interface LanguageContextType {
  language: Language;
  t: (key: string) => string;
  currentPage: Page;
  portfolioFilter: PortfolioFilter;
  setPortfolioFilter: (filter: PortfolioFilter) => void;
  selectedProjectId: string | null;
  setSelectedProjectId: (id: string | null) => void;
  navigateTo: (page: Page, projectId?: string, filter?: PortfolioFilter) => void;
  /** Register a warning shown (via confirm) before any in-app navigation that would
   *  leave the current page; pass null to clear. Used so an in-flight AI Vision
   *  generation isn't silently discarded when the user navigates away. */
  setNavGuard: (message: string | null) => void;
  /** True if navigation may proceed (no guard set, or the user confirmed the warning). */
  confirmNav: () => boolean;
}

const translations = {
  en: {
    // Nav
    'nav.home': 'Home',
    'nav.studio': 'About',
    'nav.portfolio': 'Portfolio',
    'nav.services': 'Services',
    'nav.aiStudio': 'AI Studio',
    'ai.studioBrand': 'Designature Studio',
    'nav.pricing': 'Pricing',
    'nav.contact': 'Contact',
    'nav.blog': 'Blog',
    'nav.deliverables': 'Deliverables',
    'nav.journal': 'Journal',
    'nav.bookConsultation': 'Book a Consultation',
    'nav.freeConsultation': 'Free Consultation',
    'nav.tryAiFree': 'Try AI free',
    'nav.goToStudio': 'Go to Studio',
    'nav.signOut': 'Sign out',

    // Hero
    'hero.studio2021': 'Designature Studio Est. 2021',
    'btn.explore': 'Explore Projects',

    // Services
    'serv.title': 'Our Services',
    'serv.heading': 'Everything You Need, Delivered',
    'serv.subtext': 'We bridge the gap between visionary design and technical precision.',
    'btn.example': 'View Example',
    'btn.tryAgain': 'Try Again',
    'serv.packageIncludes': 'Package Includes',
    'serv.pageHeroTitle': 'Design Services',
    'serv.pageHeroSub': 'Tailored architectural and interior design solutions for visionary clients.',
    'serv.res.title': 'Residential Design',
    'serv.res.intro': 'Creating intimate, personal sanctuaries that reflect your unique lifestyle.',
    'serv.res.list': 'Concept Development|Space Planning|Material Selection|Furniture Sourcing|Lighting Design',
    'serv.com.title': 'Commercial Design',
    'serv.com.intro': 'Strategic environments designed to enhance brand identity and productivity.',
    'serv.com.list': 'Office Layouts|Retail Interiors|Hospitality Design|Brand Integration|Technical Documentation',
    'serv.ren.title': 'Renovation & Styling',
    'serv.ren.intro': 'Breathe new life into existing spaces through thoughtful intervention.',
    'serv.ren.list': 'Structural Updates|Interior Refresh|Art Curation|Color Consultation|Final Styling',
    'serv.cta.res': 'View Residential',
    'serv.cta.com': 'View Commercial',
    'serv.cta.ren': 'View Renovation',
    'serv.final.title': 'Ready to Start?',
    'serv.final.desc': 'Let\'s transform your vision into an architectural reality.',
    'serv.final.btn': "Let's Talk",
    'services.desc': 'Our comprehensive suite of services ensures every aspect of your architectural journey is handled with precision and artistic integrity.',
    'services.downloading': 'Downloading...',
    'services.downloadFailed': 'PDF download failed, opening in new tab',

    // Process
    'proc.title': 'Our Process',
    'proc.subtext': 'A systematic approach to creativity.',
    'proc.step1.title': 'Consultation',
    'proc.step1.desc': 'Initial meeting to understand your vision, goals, and project requirements.',
    'proc.step2.title': 'Concept',
    'proc.step2.desc': 'Developing the core design philosophy and visual direction for the space.',
    'proc.step3.title': 'Design',
    'proc.step3.desc': 'Detailed architectural drawings, 3D visualizations, and material specifications.',
    'proc.step4.title': 'Refinement',
    'proc.step4.desc': 'Collaborative review and fine-tuning of every detail to ensure perfection.',
    'proc.step5.title': 'Execution',
    'proc.step5.desc': 'Project management and coordination to bring the design to life.',
    'proc.step6.title': 'Handover',
    'proc.step6.desc': 'Final walkthrough and delivery of your completed architectural masterpiece.',

    // Projects
    'pro.title': 'Featured Work',
    'pro.heading': 'Come See What We\'ve Created',
    'pro.subtext': 'These spaces started with a conversation. Take a peek at the homes and commercial spaces we have brought to life — each one designed with care.',
    'btn.viewAllProjects': 'View All Projects',

    // Portfolio
    'port.title': 'Our Portfolio',
    'port.heading': 'Curated Projects',
    'port.all': 'All',
    'port.residential': 'Residential',
    'port.commercial': 'Commercial',
    'port.detail.type': 'Project Type',
    'port.detail.area': 'Total Area',
    'port.detail.date': 'Completion',
    'port.detail.location': 'Location',
    'portfolio.title': 'Curated Spaces',
    'portfolio.back': 'BACK TO PORTFOLIO',
    'portfolio.backHome': 'BACK TO HOME',
    'portfolio.next': 'Next Experience',
    'portfolio.exploreMore': 'Explore More',
    'portfolio.return': 'Return to Gallery',
    'portfolio.mainPerspective': 'Main Perspective',
    'portfolio.detailView1': 'Detail View I',
    'portfolio.detailView2': 'Detail View II',
    'portfolio.widePerspective': 'Wide Perspective',
    'portfolio.contextView1': 'Context View I',
    'portfolio.contextView2': 'Context View II',
    'portfolio.closeup1': 'Close-up I',
    'portfolio.closeup2': 'Close-up II',
    'portfolio.closeup3': 'Close-up III',
    'portfolio.atmosphere1': 'Atmosphere I',
    'portfolio.atmosphere2': 'Atmosphere II',
    'portfolio.additionalView': 'Additional View {n}',
    'portfolio.noImage': 'No Image Available',
    'portfolio.view': 'VIEW',

    // Why Choose Us
    'why.title': 'Why Choose Us',
    'why.heading': 'We\'ve got you covered.',
    'why.desc': 'Engineering background meets design vision — every project is technically rigorous, aesthetically considered, and fully managed from concept to completion.',
    'why.label': 'Why Designature',
    'why.p1.title': 'Engineering backbone',
    'why.p1.desc': 'Every concept is structurally sound and code-compliant — not just beautiful.',
    'why.p2.title': 'Global Perspective',
    'why.p2.desc': 'International design standards and trends applied to every local project, wherever you are.',
    'why.p3.title': 'End-to-end process',
    'why.p3.desc': 'First sketch to final brick — we own the complexity so you don\'t have to manage ten contractors.',
    'why.p4.title': 'Remote-First Ready',
    'why.p4.desc': 'Full design service delivered digitally — 3D walkthroughs, live reviews, signed off remotely.',

    // AI Section
    'ai.engine': 'AI Design Studio',
    'ai.heading': 'Design First. Commit Later.',
    'ai.desc': 'Six tools. One page. Free to start.',
    'ai.uploadInsp': 'Upload Inspiration',
    'btn.change': 'Change photo',
    'btn.add': 'Add images',
    'common.optional': 'optional',
    'ai.uploadFloor': 'Upload Room Photo',
    'ai.styleQuiz': 'Style Quiz',
    'ai.aiVision': 'AI Vision',
    'ai.shoppingList': 'Shopping List',
    'ai.roomAudit': 'Room Audit',
    'ai.designBrief': 'Design Brief',
    'ai.culturalAdvisor': 'Cultural Advisor',
    'ai.remaining': 'concepts remaining',
    'ai.remainingShopping': 'shopping lists remaining',
    'ai.unlimited': 'Unlimited',
    'ai.heroCtaQuiz': 'Discover your design DNA',
    'ai.heroCtaVision': 'See your room transformed',
    'ai.heroCtaShopping': 'Find the real products',
    'ai.unlockAll': 'Unlock all tools',
    'ai.signInToStart': 'Start your AI journey',
    'ai.signInQuiz': 'Discover your design DNA',
    'ai.signInVision': 'See your room transformed',
    'ai.signInShopping': 'Find the real products',
    'ai.noCard': 'No credit card required',
    'ai.toExplore': 'to explore',
    'ai.liveTools': 'live AI tools',
    'ai.discoverDNA': 'Discover your design DNA',
    'ai.transformRoom': 'Transform your room',
    'ai.shopInterior': 'Shop any interior',
    'ai.scoreSpace': 'Score your space',
    'ai.buildBrief': 'Build your brief',
    'ai.blendStyles': 'Blend global styles',
    'ai.nowActive': 'Live',
    'nav.backToHome': 'Back to Home',
    'ai.jumpToTool': 'Jump to any tool above',
    'ai.quizDesc': 'Rate 18 rooms · Get your design DNA · Apply to AI Vision',
    'ai.visionDesc': 'Upload your room · Choose a style · Generate your concept',
    'ai.shopDesc': 'Upload any interior · Find real products · Download PDF',
    // ── Shopping List (03) redesign — logged-out 4-room explorer ──
    'ai.shop.statusSample': 'Shopping List · Sample gallery',
    'ai.shop.signInLink': 'Sign in',
    'ai.shop.sampleRoom': 'Sample room',
    'ai.shop.piecesMatched': '4 pieces matched',
    'ai.shop.heroTitle': 'Any room,',
    'ai.shop.heroTitleEm': 'shoppable.',
    'ai.shop.heroSub': 'Point at any interior — we spot every piece and match real products you can buy today.',
    'ai.shop.heroSubBold': "Explore four rooms we've already shopped, free.",
    'ai.shop.exploreCta': '↓ Explore the sample lists',
    'ai.shop.shopYourRoom': 'Shop your own room →',
    'ai.shop.heroCap': 'Every piece · matched to a real product you can buy',
    'ai.shop.v1k': '1 · Upload',
    'ai.shop.v1b': 'A photo, a Pinterest pin, or an AI Vision concept.',
    'ai.shop.v2k': '2 · Match',
    'ai.shop.v2b': 'AI finds the real products across top retailers.',
    'ai.shop.v3k': '3 · Shop',
    'ai.shop.v3b': 'One best pick each, with a PDF to take to checkout.',
    'ai.shop.exploreKicker': 'See it in action',
    'ai.shop.exploreTitle': 'Four rooms,',
    'ai.shop.exploreTitleEm': 'already shopped.',
    'ai.shop.exploreSub': "Pick a room. Every link is a real piece at a real store. This is exactly what you'll get for your own room once you sign in.",
    'ai.shop.matched': 'matched',
    'ai.shop.roomHint': 'Each product links to a real page you can buy from today.',
    'ai.shop.theList': 'The shopping list',
    'ai.shop.estTotal': 'Est. total',
    'ai.shop.viewAt': 'View at',
    'ai.shop.makeForMyRoom': '+ Make this list for MY room →',
    'ai.shop.downloadPdf': '⬇ Download PDF',
    'ai.shop.saveList': '♥ Save list',
    'ai.shop.footnote': 'Browsing samples is free.',
    'ai.shop.footnote2': 'to shop your own room, save lists, and download a PDF.',
    'ai.shop.searchedAcross': 'Searched across',
    'ai.shop.convKicker': 'Got a room in mind?',
    'ai.shop.convHeadline': 'Shop it the same way —',
    'ai.shop.convHeadlineEm': 'in seconds.',
    'ai.shop.signInToStart': 'Sign in to start →',
    'ai.shop.bookStudio': 'Book the studio',
    'ai.shop.veilKicker': 'Designature Studio',
    'ai.shop.veilTitle': 'Build your',
    'ai.shop.veilTitleEm': 'shopping list.',
    'ai.shop.veilLead': "You're one step from",
    'ai.shop.veilNote': 'Free to start · no card needed · we never post or share without your say-so.',
    'ai.shop.veilGoogle': 'Continue with Google',
    'ai.shop.veilFineprint': 'Your three free lists are waiting on the other side.',
    'ai.shop.veilDismiss': 'Keep browsing samples',
    'ai.shop.reasonShop': 'shopping your own room',
    'ai.shop.reasonDownload': 'downloading this list as a PDF',
    'ai.shop.reasonSave': 'saving this list',
    // ── Shopping List (03) redesign — LOGGED-IN 4-state ──
    'ai.shopli.listsLeft': 'lists left this month',
    'ai.shopli.statusReady': 'Shopping List · Ready',
    'ai.shopli.yourRoom': 'Your room',
    'ai.shopli.itemsFound': '4 items found',
    'ai.shopli.heroTitle': 'Any room,',
    'ai.shopli.heroTitleEm': 'shoppable.',
    'ai.shopli.heroSub': 'We spot every piece of furniture and match real products you can actually buy.',
    'ai.shopli.uploadCta': '+ Upload your room →',
    'ai.shopli.shopConcept': 'Shop my AI Vision concept',
    'ai.shopli.heroCap': 'Every pin · matched to a real product you can buy',
    'ai.shopli.v1k': '1 · Upload',
    'ai.shopli.v1b': 'A photo, a Pinterest pin, or an AI Vision concept.',
    'ai.shopli.v2k': '2 · Match',
    'ai.shopli.v2b': 'AI finds the real products across top retailers.',
    'ai.shopli.v3k': '3 · Shop',
    'ai.shopli.v3b': 'One best pick each, alternatives, and a PDF to take.',
    'ai.shopli.entryTitle': 'Find what to',
    'ai.shopli.entryTitleEm': 'shop.',
    'ai.shopli.imageShopping': "The image you're shopping",
    'ai.shopli.changeImage': '↺ Change image',
    'ai.shopli.sourceCaption': 'Your AI Vision concept — or upload any photo',
    'ai.shopli.yourSearch': 'Your search',
    'ai.shopli.allFurniture': 'All furniture',
    'ai.shopli.spottedLine': 'We spotted the pieces ready to match.',
    'ai.shopli.whereToShop': 'Where to shop',
    'ai.shopli.setsRetailers': 'sets retailers & prices',
    'ai.shopli.country': 'Country',
    'ai.shopli.paid': 'Paid',
    'ai.shopli.find': 'Find',
    'ai.shopli.findAll': 'All',
    'ai.shopli.multiSelect': 'pick any',
    'ai.shopli.allCats': 'All categories',
    'ai.shopli.categoriesSel': 'categories',
    // ── Canonical Shopping taxonomy labels (single source of truth · shoppingTaxonomy.ts) ──
    'ai.taxonomy.seating': 'Seating',
    'ai.taxonomy.tablesDesks': 'Tables & desks',
    'ai.taxonomy.storage': 'Storage',
    'ai.taxonomy.beds': 'Beds',
    'ai.taxonomy.lighting': 'Lighting',
    'ai.taxonomy.rugs': 'Rugs',
    'ai.taxonomy.textiles': 'Textiles',
    'ai.taxonomy.artDecor': 'Art & decor',
    'ai.shopli.scope.allFurniture': 'All furniture',
    'ai.shopli.scope.seating': 'Seating only',
    'ai.shopli.scope.lighting': 'Lighting only',
    'ai.shopli.scope.tablesStorage': 'Tables & storage',
    'ai.shopli.scope.decor': 'Decor & textiles',
    'ai.shopli.optionalRefinements': 'Optional refinements',
    'ai.shopli.refinementsHint': 'Budget, brands, exclusions',
    'ai.shopli.budgetPerItem': 'Budget per item',
    'ai.shopli.budget.any': 'Any',
    'ai.shopli.budget.value': 'Value',
    'ai.shopli.budget.mid': 'Mid',
    'ai.shopli.budget.premium': 'Premium',
    // ── Budget LEVEL model (relative, per-category) ──
    'ai.shopli.budgetLevel': 'Budget level',
    'ai.shopli.budgetLevelHelp': 'Pick a level — we shop that quality in every category, so each piece is judged on its own type.',
    'ai.shopli.budgetSub.any': 'No limit',
    'ai.shopli.budgetSub.value': 'Budget-friendly',
    'ai.shopli.budgetSub.mid': 'Mid-range',
    'ai.shopli.budgetSub.premium': 'High-end',
    'ai.shopli.whatMean': 'What do these mean?',
    'ai.shopli.bandsNoFilter': 'No price filter — all retailers',
    'ai.shopli.bandsHead': 'At {level}, typical price per category',
    'ai.shopli.bandAny': 'any',
    'ai.shopli.bandsCaption': 'Bands per category come from our retailer tiers.',
    'ai.shopli.capLabel': 'Cap the whole-room budget',
    'ai.shopli.optional': 'optional',
    'ai.shopli.keepUnder': 'Keep total under',
    'ai.shopli.capNote': 'Level set to Any — we pick across all price levels and keep your total within budget.',
    'ai.shopli.overCap': 'over budget',
    'ai.shopli.categories': 'Categories to include',
    'ai.shopli.findProducts': '🛒 Find products in this image →',
    'ai.shopli.sec': 'sec',
    'ai.shopli.freeComplete': 'Free tier complete',
    'ai.shopli.usedAll': "You've used your 3 free lists.",
    'ai.shopli.upgrade': 'See plans',
    'ai.shopli.theItem': 'the item',
    'ai.shopli.identifying': 'Identifying products…',
    'ai.shopli.usingOne': 'Using 1 of your {n} lists',
    'ai.shopli.searchingPhrase': 'Searching across our curated retailers…',
    'ai.shopli.listReady': 'List ready · {n} items',
    'ai.shopli.startOver': '↺ Start over',
    'ai.shopli.yourInterior': 'Your interior',
    'ai.shopli.fromUpload': 'Matched from your uploaded photo.',
    'ai.shopli.fromConcept': 'Matched from your AI Vision concept.',
    'ai.shopli.yourList': 'Your shopping list',
    'ai.shopli.items': 'items',
    'ai.shopli.groupBy': 'Group by',
    'ai.shopli.listOrder': 'List order',
    'ai.shopli.budgetTier': 'Budget tier',
    'ai.shopli.roomZone': 'Room zone',
    'ai.shopli.moreRetailers': 'more retailer options',
    'ai.shopli.findAnother': '↻ Find another option',
    'ai.shopli.findingAlt': 'Finding another option…',
    'ai.shopli.noAltFound': 'No other option found — try a different item.',
    'ai.shopli.downloadPdf': '⬇ Download this list (PDF)',
    'ai.shopli.saveList': '♥ Save list to my favourites',
    'ai.shopli.disclaimer': 'AI-matched — verify dimensions, material & price before buying.',
    'ai.shopli.convKicker': 'Want it sourced & delivered?',
    'ai.shopli.convHeadline': 'Let the studio',
    'ai.shopli.convHeadlineEm': 'handle it.',
    'ai.shopli.bookStudio': 'Book the studio →',
    'ai.shopli.estTotal': 'Est. total',
    'ai.shopli.favourite': 'Favourite',
    'ai.shopli.include': 'Include in list',
    'ai.shopli.setAsBest': 'Set as best',
    'ai.shopli.editSearch': '✎ Edit search',
    'ai.shopli.backToList': 'Back to your list',
    'ai.shopli.budgetLabel': 'Budget',
    'ai.shopli.noneSel': 'No categories',
    'ai.shopli.freeCountLine': 'Found {m} items · showing {n} (free) — upgrade for the rest',
    'ai.shopli.teaserTitle': 'We also spotted in your room',
    'ai.shopli.upgradeToShop': 'See plans — unlock {n} more →',
    'ai.auditDesc': 'Get a scored report card for any room with actionable fixes',
    // ── Room Audit · in-studio paid landing (free + logged-out) ──
    'ai.audit.sampleKicker': 'A sample audit',
    'ai.audit.overallScore': 'Overall score',
    'ai.audit.pin1Title': 'Lighting',
    'ai.audit.pin1Note': 'Strong natural light — lean into it with sheer layers.',
    'ai.audit.pin2Title': 'Empty corner',
    'ai.audit.pin2Note': 'Add height — a plant or floor lamp to anchor it.',
    'ai.audit.pin3Title': 'Rug scale',
    'ai.audit.pin3Note': 'Too small for the seating — size up so front legs sit on it.',
    'ai.audit.badge': 'Design+ feature',
    'ai.audit.valueLine': "An honest, professional read on the room you have right now. Upload a photo and get a designer's critique — ",
    'ai.audit.valueLineBold': 'what works, what to fix, and the quick wins.',
    'ai.audit.scoredAcross': 'Scored across 6 design metrics',
    'ai.audit.metricLayout': 'Layout & flow',
    'ai.audit.metricLighting': 'Lighting',
    'ai.audit.metricColour': 'Colour & palette',
    'ai.audit.metricProportion': 'Proportion & scale',
    'ai.audit.metricMaterials': 'Materials & texture',
    'ai.audit.metricStyling': 'Styling & balance',
    'ai.audit.unlockCta': 'Unlock with Design+ — $19/mo',
    'ai.audit.upgradeCta': 'Upgrade to Design+ — $19/mo',
    'ai.audit.seeSample': 'See a full sample audit',
    'ai.audit.signInCta': 'Sign in to get started',
    'ai.audit.seePlans': 'See plans & pricing',
    'ai.audit.ctaNoteOut': 'Cancel anytime · no commitment.',
    'ai.audit.alreadyMember': 'Already a member? Sign in',
    'ai.audit.ctaNoteFree': 'Design+ unlocks Room Audit, unlimited Style Quiz, and more. Cancel anytime.',
    // ── Room Audit (04) logged-in PAID 4-state experience (RoomAuditExperience) ──
    'ai.audit.statusReady': 'Room Audit · Ready',
    'ai.audit.statusAnalyzing': 'Analyzing your room…',
    'ai.audit.statusComplete': 'Audit complete',
    'ai.audit.quotaUnlimited': 'Unlimited audits · Design+',
    'ai.audit.quotaLeft': '{n} audits left',
    'ai.audit.usingOne': 'Using 1 audit',
    'ai.audit.heroKicker': 'Room Audit',
    'ai.audit.heroTitle': 'Your room,',
    'ai.audit.heroTitleEm': 'scored.',
    'ai.audit.heroSub': "An honest designer's read on the space you have — what works, what to fix, and the quick wins worth doing first.",
    'ai.audit.heroOverall': 'Overall',
    'ai.audit.heroOverallMeta': '/ 100 · B',
    'ai.audit.dimsScored': '6 dimensions scored',
    'ai.audit.uploadCta': '+ Upload your room →',
    'ai.audit.sampleCta': 'Score a sample room',
    'ai.audit.sampleLoading': 'Loading sample…',
    'ai.audit.heroCap': "Every score · backed by a designer's reasoning",
    'ai.audit.v1k': '1 · Upload',
    'ai.audit.v1b': 'A photo of the room as it is today.',
    'ai.audit.v2k': '2 · Analyze',
    'ai.audit.v2b': 'AI scores six design dimensions and explains each.',
    'ai.audit.v3k': '3 · Improve',
    'ai.audit.v3b': 'Get the top three fixes worth doing first.',
    'ai.audit.scoredAcrossLabel': 'Scored across',
    // the six REAL server dimensions (marquee + veil-phrase) — kept honest
    'ai.audit.dimLayout': 'Layout & flow',
    'ai.audit.dimLighting': 'Lighting',
    'ai.audit.dimColor': 'Color harmony',
    'ai.audit.dimClutter': 'Clutter & organization',
    'ai.audit.dimFunction': 'Functionality',
    'ai.audit.dimStyle': 'Style cohesion',
    'ai.audit.setupTitle': 'Score your',
    'ai.audit.setupTitleEm': 'space.',
    'ai.audit.theRoom': "The room you're scoring",
    'ai.audit.changePhoto': '↺ Change photo',
    'ai.audit.uploadHint': 'Upload any room photo · JPG, PNG · max 10MB',
    'ai.audit.sampleInstead': 'Score a sample instead',
    'ai.audit.yourAudit': 'Your audit',
    'ai.audit.wholeRoom': 'Whole room',
    'ai.audit.noGoals': 'no goals set',
    'ai.audit.oneGoal': '1 goal set',
    'ai.audit.manyGoals': '{n} goals set',
    'ai.audit.summaryLine': "We'll score six design dimensions and flag the fixes worth doing first.",
    'ai.audit.step1': 'Your room photo',
    'ai.audit.step1Ready': 'ready ✓',
    'ai.audit.step1Body': 'Shown on the left. Use a wide, well-lit shot of the whole room for the most accurate read.',
    'ai.audit.step2': 'Your goals',
    'ai.audit.optional': '(optional)',
    'ai.audit.step2Body': "Tell us what you're after and the audit weighs its advice toward it.",
    'ai.audit.goal.cozy': 'Make it cozier',
    'ai.audit.goal.storage': 'More storage',
    'ai.audit.goal.flow': 'Better flow',
    'ai.audit.goal.light': 'Maximize light',
    'ai.audit.goal.style': 'Elevate style',
    'ai.audit.goal.minimal': 'Reduce clutter',
    'ai.audit.refinements': 'Optional refinements',
    'ai.audit.refinementsHint': 'Room type, notes',
    'ai.audit.roomTypeLabel': 'Room type',
    'ai.audit.roomTypeOptional': '— optional',
    'ai.audit.room.living': 'Living room',
    'ai.audit.room.bedroom': 'Bedroom',
    'ai.audit.room.dining': 'Dining',
    'ai.audit.room.kitchen': 'Kitchen',
    'ai.audit.room.office': 'Office',
    'ai.audit.room.bathroom': 'Bathroom',
    'ai.audit.room.outdoor': 'Outdoor',
    'ai.audit.notesLabel': 'Anything we should know?',
    'ai.audit.notesPlaceholder': 'e.g. north-facing, renting so no painting, two cats…',
    'ai.audit.scoreCta': '✦ Score my room →',
    'ai.audit.scoreEta': '~20 sec',
    'ai.audit.assessing': 'Assessing',
    'ai.audit.auditAnother': '↺ Audit another room',
    'ai.audit.annotatedKicker': 'Your room · annotated',
    'ai.audit.annotatedHint': 'Pins mark the quick wins below — tap one to jump to it.',
    'ai.audit.reportKicker': 'Your audit',
    'ai.audit.overallLabel': 'Overall',
    'ai.audit.weightedNote': 'Weighted average of six design dimensions, each scored out of ten.',
    'ai.audit.detailedBreakdown': 'Detailed breakdown',
    'ai.audit.fixNowTitle': 'Fix now · top 3 quick wins',
    'ai.audit.redesignVision': '→ Redesign this room with AI Vision',
    'ai.audit.reportDisclaimer': "A designer's read, powered by AI — your space, your call.",
    'ai.audit.convKicker': 'Want these fixes done for you?',
    'ai.audit.convHeadline': 'Let the studio',
    'ai.audit.convHeadlineEm': 'handle it.',
    'ai.audit.bookStudio': 'Book the studio →',
    'ai.audit.errorGeneric': 'Audit failed. Please try again.',
    'ai.audit.outOf': '/ 10',
    // ── AI Vision (02) redesign — logged-out explorer + logged-in 4-state ──
    'ai.vision.statusSample': 'AI Vision · Sample gallery',
    'ai.vision.signIn': 'Sign in',
    'ai.vision.before': 'Before',
    'ai.vision.after': 'After',
    'ai.vision.heroTitle': 'Your room,',
    'ai.vision.heroTitleEm': 'reimagined.',
    'ai.vision.heroSub': 'Drop a photo, pick a style, watch it transform in thirty seconds.',
    'ai.vision.heroSubBold': 'Drag four real before/afters below, free.',
    'ai.vision.exploreCta': '↓ Explore the transformations',
    'ai.vision.uploadYourRoom': 'Upload your room →',
    'ai.vision.dragCompare': '← Drag to compare · before / after',
    'ai.vision.v1k': '1 · Upload',
    'ai.vision.v1b': 'A photo of any room — yours or one you love.',
    'ai.vision.v2k': '2 · Inspire',
    'ai.vision.v2b': 'Add reference photos or a Pinterest board.',
    'ai.vision.v3k': '3 · Reimagine',
    'ai.vision.v3b': 'Three concepts to keep, share, or shop.',
    'ai.vision.exploreKicker': 'See it in action',
    'ai.vision.exploreTitle': 'Four real rooms,',
    'ai.vision.exploreTitleEm': 'reimagined.',
    'ai.vision.exploreSub': 'Pick a transformation. Drag the slider to reveal the before. This is exactly what AI Vision does to your own room once you sign in.',
    'ai.vision.genTime': '~30 sec to generate',
    'ai.vision.dragHint': '← Drag to compare. Pick another transformation above to load it here.',
    'ai.vision.whatChanged': 'What the AI changed',
    'ai.vision.reimagineMyRoom': '✦ Reimagine MY room →',
    'ai.vision.download': '⬇ Download',
    'ai.vision.shopThisRoom': '🛒 Shop this room',
    // AI Vision result conversion band (end-of-funnel booking)
    'ai.vision.bandKicker': 'Love what you see?',
    'ai.vision.bandHeadline': 'Ready to',
    'ai.vision.bandHeadlineEm': 'make it real?',
    'ai.vision.getDesigned': 'Get this designed',
    'ai.vision.exploreFootnote': 'Browsing samples is free.',
    'ai.vision.exploreFootnote2': 'for 3 free generations of your own room — no card needed.',
    'ai.vision.anyStyle': 'Any style',
    'ai.vision.convKicker': 'Got a room in mind?',
    'ai.vision.convHeadline': 'See it transformed —',
    'ai.vision.convHeadlineEm': 'in thirty seconds.',
    'ai.vision.signInToStart': 'Sign in to start →',
    'ai.vision.veilKicker': 'Designature Studio',
    'ai.vision.veilTitle': 'See your room,',
    'ai.vision.veilTitleEm': 'reimagined.',
    'ai.vision.veilLead': "You're one step from",
    'ai.vision.veilNote': 'Free to start · 3 generations · no card needed · we never post or share without your say-so.',
    'ai.vision.veilGoogle': 'Continue with Google',
    'ai.vision.veilFineprint': 'Your three free generations are waiting on the other side.',
    'ai.vision.veilDismiss': 'Keep browsing samples',
    'ai.vision.reasonReimagine': 'reimagining your own room',
    'ai.vision.reasonDownload': 'downloading this concept',
    'ai.vision.reasonShop': 'shopping the products in this concept',
    // Setup (logged-in) extras
    'ai.vision.setupTitle': 'Set up your',
    'ai.vision.setupTitleEm': 'concept.',
    'ai.vision.yourConcept': 'Your concept',
    'ai.vision.autoRoom': 'Auto room',
    'ai.vision.autoStyle': 'Auto style',
    'ai.vision.step1Inspiration': 'Add your inspiration',
    'ai.vision.step1Required': 'at least one required',
    'ai.vision.step1Help': 'Reference photos, a Pinterest board, or both — these shape the look, not the room itself.',
    'ai.vision.theRoom': "The room you're redesigning",
    'ai.vision.changePhoto': '↺ Change photo',
    'ai.vision.keepProportions': 'Any format · any size — we keep your original proportions',
    'ai.vision.summaryLine': 'We spotted your room — {n} inspiration(s) added.',
    'ai.vision.optionalRefinements': 'Optional refinements',
    'ai.vision.autoDetected': 'Style & room — auto-detected',
    'ai.vision.chooseStyle': 'Choose a style',
    'ai.vision.roomType': 'Room type',
    'ai.vision.generatingUsually': 'Usually under 30 seconds',
    // before/after transformation pairs
    'ai.vision.pair.midcentury.style': 'Mid-Century',
    'ai.vision.pair.midcentury.kicker': 'Mid-Century · living room',
    'ai.vision.pair.midcentury.name': 'Empty shell → warm sanctuary',
    'ai.vision.pair.midcentury.desc': 'An empty shell becomes a Mid-Century living space — soft sofa, warm light, and pieces that earn their place.',
    'ai.vision.pair.midcentury.c1': 'Walnut tones & clean, low lines',
    'ai.vision.pair.midcentury.c2': 'Warm, layered lighting',
    'ai.vision.pair.midcentury.c3': 'Furniture that earns its place',
    'ai.vision.pair.minimalism.style': 'Minimalism',
    'ai.vision.pair.minimalism.kicker': 'Minimalism · living room',
    'ai.vision.pair.minimalism.name': 'Bare shell → calm living room',
    'ai.vision.pair.minimalism.desc': "A bare-shell room transformed into a calm Minimalism living space — full ceiling, full floor, the room you'd actually walk into.",
    'ai.vision.pair.minimalism.c1': 'Full ceiling & floor rebuilt',
    'ai.vision.pair.minimalism.c2': 'Soft, even natural light',
    'ai.vision.pair.minimalism.c3': 'Pared-back, intentional pieces',
    'ai.vision.pair.bohemian.style': 'Bohemian',
    'ai.vision.pair.bohemian.kicker': 'Bohemian · bedroom',
    'ai.vision.pair.bohemian.name': 'Plain bedroom → layered retreat',
    'ai.vision.pair.bohemian.desc': 'A bare room reimagined as a Bohemian bedroom — rattan chair, layered rug, and soft window light.',
    'ai.vision.pair.bohemian.c1': 'Rattan & natural texture',
    'ai.vision.pair.bohemian.c2': 'Layered rugs & textiles',
    'ai.vision.pair.bohemian.c3': 'Soft, diffused window light',
    'ai.vision.pair.contemporary.style': 'Contemporary',
    'ai.vision.pair.contemporary.kicker': 'Contemporary · lounge',
    'ai.vision.pair.contemporary.name': 'Bright room → refined lounge',
    'ai.vision.pair.contemporary.desc': 'An empty bright room turned into a refined Contemporary lounge — clean lines, a soft palette, an inviting calm.',
    'ai.vision.pair.contemporary.c1': 'Clean architectural lines',
    'ai.vision.pair.contemporary.c2': 'Soft, current palette',
    'ai.vision.pair.contemporary.c3': 'An inviting, easy calm',
    'ai.usedAll': "You've used all 3 free generations.",
    'ai.bookConversation': "Let's Talk",
    'ai.generateConcept': 'Generate concept',
    'ai.conceptAppear': 'Your concept will appear here',
    'ai.completeSteps': 'Complete the steps on the left',
    'ai.processingTime': 'This takes about 20–40 seconds',
    'ai.searchFailed': 'Search failed. Please try again.',
    'ai.spatialLogic': 'Spatial Logic',
    'ai.spatialDesc': 'AI analyzes structural flow and optimization.',
    'ai.materialSynthesis': 'Material Synthesis',
    'ai.materialDesc': 'Intelligent texture and color palette generation.',
    'ai.volumeAnalysis': 'Volume Analysis',
    'ai.volumeDesc': '3D massing studies based on 2D inputs.',
    'ai.images': 'images',
    'ai.style.japandi': 'Japandi',
    'ai.style.warmcontemporary': 'Warm Contemporary',
    'ai.style.trend2026': 'Trend 2026',
    'ai.style.modern': 'Modern',
    'ai.style.midCentury': 'Mid-Century',
    'ai.style.midcentury': 'Mid-Century',
    'ai.style.bohemian': 'Bohemian',
    'ai.style.rustic': 'Rustic',
    'ai.style.dopamine': 'Dopamine',
    'ai.style.minimalist': 'Minimalist',
    'ai.style.industrial': 'Industrial',
    'ai.style.maximalist': 'Maximalist',
    'ai.style.coastal': 'Coastal',
    'ai.style.artDeco': 'Art Deco',
    'ai.style.artdeco': 'Art Deco',
    'ai.style.transitional': 'Transitional',
    'ai.style.art deco': 'Art Deco',
    'common.processing': 'Processing',
    'ai.shopThisLook': 'Shop This Look',
    'ai.shopThisLookDesc': 'Find the real products from this concept.',
    'ai.findTheseProducts': 'Find These Products',
    'ai.style.biophilic': 'Biophilic',
    'ai.style.scandinavian': 'Scandinavian',
    'ai.style.traditional': 'Traditional',
    'ai.designComplete': 'Design Complete',
    'ai.genVariation': 'Generate variation (uses 1)',
    'btn.reset': 'Reset',
    'ai.originalRoom': 'Original Room',
    'ai.genConcept': 'Generated Concept',
    'ai.genConcepts': 'Generated Concepts',
    'ai.sessionConceptsArchive': 'Earlier this session',
    'ai.sessionConceptsArchiveHint': 'Kept only until you log out or close this page — download to keep a copy.',
    'aiVision.inspiration.tip.body': 'Tip: add 2–3 reference images for best results. Multiple angles and details give the AI a richer spatial understanding of the style you want.',
    'aiVision.sidebar.sectionStyle': 'Style',
    'aiVision.gallery.sampleAlreadyRun': 'Loved the sample? Now try it with your own room \u2014 upload a photo above to get started.',
    'btn.downloadFull': 'Download Full Resolution',
    'btn.downloadAll': 'Download All',
    'ai.quiz.roomOf': 'Room {current} of {total}',
    'ai.quiz.startOver': 'Start over',
    'ai.quiz.rateHonestly': 'Rate each space honestly',
    'ai.quiz.fromPortfolio': 'From our portfolio',
    'ai.quiz.howFeel': 'How do you feel about this space?',
    'ai.quiz.loveIt': 'Love it',
    'ai.quiz.skip': 'Skip',
    'ai.quiz.notMyStyle': 'Not my style',
    'ai.quiz.tasteSoFar': 'Your taste so far',
    'ai.quiz.designDNA': 'Your design DNA',
    'ai.quiz.basedOnRatings': 'Based on your ratings',
    'ai.quiz.applyStyle': 'Apply {style} style to AI Vision',
    'ai.quiz.retake': 'Retake quiz',
    'ai.quiz.stylePreselected': 'Your top style ({style}) will be pre-selected in AI Vision so your first concept matches your taste.',
    'ai.quiz.heroTitle': 'Find your design DNA in two minutes.',
    'ai.quiz.heroLead': "Rate 18 rooms. We'll show you the styles, materials, and palettes you actually love — then carry them straight into AI Vision.",
    'ai.quiz.step1Title': 'Rate 18 rooms',
    'ai.quiz.step1Body': "Love it, skip it, or pass. About two minutes. We'll tell you when you've shown us enough.",
    'ai.quiz.step2Title': 'See your design DNA',
    'ai.quiz.step2Body': 'A primary style, a secondary style, and the percentages — the language behind your taste.',
    'ai.quiz.step3Title': 'Carry it into AI Vision',
    'ai.quiz.step3Body': 'One click and your style auto-applies to every render you generate from there on.',
    'ai.quiz.signInCta': 'Sign in with Google to start',
    'ai.quiz.heroMeta': 'Free · 18 rooms · 2 minutes · No card needed',
    'ai.quiz.eightStyles': 'Eight styles in the quiz',
    'ai.quiz.previewCaption': 'Frame from the actual quiz',
    'ai.quiz.favorites': 'Favorites',
    'ai.quiz.previous': '← Previous',
    'ai.quiz.notForMe': '✕ Not for me',
    'ai.quiz.loveItStar': '✦ Love it',
    'ai.quiz.haveEnough': 'I have enough — show me my style →',
    'ai.quiz.stageCaption': 'One room at a time · vote · the next room appears',
    'ai.quiz.drawerTitle': 'Your favorites',
    'ai.quiz.drawerCount': '{loved} of {total} loved',
    'ai.quiz.leadingStyles': 'Leading styles',
    'ai.quiz.dnaEyebrow': 'Your design DNA',
    'ai.quiz.styleBreakdown': 'Your style breakdown',
    'ai.quiz.actionsTitle': 'Carry your style into a render',
    'ai.quiz.whatNext': "What's next",
    'ai.quiz.moreInStyle': 'More rooms in your style',
    'ai.quiz.moreInStyleCount': '{count} rooms tagged {style}',
    'ai.quiz.applyVision': '✦ Apply to AI Vision →',
    'ai.quiz.share': 'Share with a friend',
    'ai.quiz.saveStyle': 'Save my style',
    'ai.quiz.shareToast': 'Link copied — your friend will see your DNA',
    'ai.quiz.savedToast': 'Saved to My account — find it in your Library',
    'ai.quiz.upgradeToSave': 'Save your DNA with the Design tier — $19/mo',
    'ai.quiz.sharedBanner': 'Viewing a shared style',
    'ai.quiz.takeYourQuiz': 'Take your own quiz →',
    // ── Style Quiz v4 redesign (locked mockup port) ──
    'ai.quiz.statusReady': 'Style Quiz · Ready',
    'ai.quiz.signIn': 'Sign in',
    'ai.quiz.alwaysFree': 'Unlimited · always free',
    'ai.quiz.playingGuest': 'Playing as guest · no account needed',
    'ai.quiz.tryNow': 'Try it now',
    'ai.quiz.whichRooms1': 'Which rooms',
    'ai.quiz.whichRooms2': 'speak to you?',
    'ai.quiz.trustGut': 'Trust your gut — first reaction is right',
    'ai.quiz.deckCap': 'No names while you swipe — react to the feeling',
    'ai.quiz.previousRoom': 'Previous room',
    'ai.quiz.lovesSoFar': 'Your loves so far',
    'ai.quiz.lovesSummary': '{n} rooms saved · reading {lean}',
    'ai.quiz.patternShowing': 'A pattern is starting to show.',
    'ai.quiz.savedRooms': 'Saved rooms',
    'ai.quiz.tapRevisit': 'tap to revisit',
    'ai.quiz.lovesEmpty': 'Hit Love it on a room to start building your taste profile.',
    'ai.quiz.keepSwiping': 'Or keep swiping — the more rooms you react to, the sharper your DNA reads.',
    'ai.quiz.stylesYoullMeet': "Styles you'll meet",
    'ai.quiz.resultReady': 'Your design DNA · ready',
    'ai.quiz.readFrom': 'Read from the {count} rooms you loved. Retake any time to refine.',
    'ai.quiz.saveFreeNote': 'Taking the quiz is always free. Saving your DNA to reuse across tools is a Studio feature.',
    'ai.quiz.savePaidNote': 'Your DNA is saved to your profile and pre-fills every tool.',
    'ai.quiz.lockStudio': 'Studio',
    'ai.quiz.lo.badge': 'Free · no sign-up to play',
    'ai.quiz.lo.title1': 'Swipe rooms.',
    'ai.quiz.lo.title2': 'Meet your style.',
    'ai.quiz.lo.sub': 'React to real rooms across fourteen design styles — love or pass, no wrong answers. In two minutes we name the look that’s unmistakably you.',
    'ai.quiz.lo.subStrong': 'Play the whole quiz free, no account.',
    'ai.quiz.lo.cta': '↓ Start swiping — it’s free',
    'ai.quiz.lo.note': 'Sign in only to save & carry it across tools',
    'ai.quiz.lo.cap': '~18 rooms · 14 styles · about 2 minutes · stop early any time',
    'ai.quiz.vs.k1': '1 · Swipe',
    'ai.quiz.vs.b1': 'React to real rooms — love the ones that pull you in.',
    'ai.quiz.vs.k2': '2 · Reveal',
    'ai.quiz.vs.b2': 'We read the pattern behind what you chose.',
    'ai.quiz.vs.k3': '3 · Apply',
    'ai.quiz.vs.b3Guest': 'Sign in to carry your DNA into AI Vision.',
    'ai.quiz.vs.b3User': 'Carry your DNA straight into AI Vision.',
    'ai.quiz.li.badge': 'Step 01 · Find your taste',
    'ai.quiz.li.title1': 'Find your',
    'ai.quiz.li.title2': 'design DNA.',
    'ai.quiz.li.sub': 'Swipe through real rooms. Love or pass — no wrong answers. In two minutes we name the styles that are unmistakably you.',
    'ai.quiz.li.startCta': '✦ Start the quiz →',
    'ai.quiz.li.sampleResult': 'See a sample result',
    'ai.quiz.li.cap': '~18 rooms · about 2 minutes · stop early any time',
    'ai.quiz.readingTitle': 'Reading your taste…',
    'ai.quiz.readingQuota': 'No generation used · free',
    'ai.quiz.readingCount': '{n} rooms loved · cross-referencing',
    'ai.quiz.readingPhrase1': 'Finding the threads that',
    'ai.quiz.readingPhrase2': 'connect what you love…',
    'ai.quiz.readingSecs': 'A few seconds',
    'ai.quiz.conv.kicker': 'Know your style?',
    'ai.quiz.conv.guest1': 'Save it and',
    'ai.quiz.conv.guest2': 'make it real.',
    'ai.quiz.conv.user1': 'Let’s',
    'ai.quiz.conv.user2': 'make it real.',
    'ai.quiz.conv.book': 'Book a conversation →',
    'ai.quiz.conv.signinSave': 'Sign in to save →',
    'ai.quiz.saveModalTitle': 'Save your style — Design tier feature',
    'ai.quiz.saveModalBody': 'Saving your design DNA to your dashboard is part of the Design tier ($19/mo). Want to review pricing?',
    'ai.quiz.viewPricing': 'See plans →',
    'ai.quiz.maybeLater': 'Maybe later',
    'ai.quiz.veil.kicker': 'Designature Studio',
    'ai.quiz.veil.title1': 'Save your',
    'ai.quiz.veil.title2': 'design DNA.',
    'ai.quiz.veil.lead': 'You’re one step from {reason}.',
    'ai.quiz.veil.note': 'Your quiz answers carry over — nothing is lost.',
    'ai.quiz.veil.google': 'Continue with Google',
    'ai.quiz.veil.fine': 'Free to create. We never post or share without your say-so.',
    'ai.quiz.veil.dismiss': 'Keep playing as guest',
    'ai.quiz.reason.save': 'saving your result',
    'ai.quiz.reason.apply': 'applying your style to AI Vision',
    'ai.quiz.reason.share': 'sharing your result',
    'ai.quiz.reason.saveStyle': 'saving your style',
    'ai.shop.signIn': 'Use the Shopping List',
    'ai.shop.shopIn': 'Shop in:',
    'ai.shop.anyInterior': 'Shop Any Interior',
    'ai.shop.anyInteriorDesc': 'Upload any interior photo and we will find the real products in it.',
    'ai.shop.imageReady': 'Image ready',
    'ai.shop.findProducts': 'Find Products',
    'ai.shop.change': 'Change',
    'ai.shop.uploadPhoto': 'Upload an Interior Photo',
    'ai.shop.newConcept': 'New Concept Generated',
    'ai.shop.newConceptDesc': 'Re-search to find products matching this new concept.',
    'ai.shop.reSearch': 'Re-Search Products',
    'ai.shop.identifying': 'Identifying furniture & searching shops...',
    'ai.shop.processingTime': 'About 15-20 seconds',
    'ai.shop.itemsIdentified': '{count} items identified:',
    'ai.shop.items': '{count} items',
    'ai.shop.noProducts': 'No products found. Try a different concept.',
    'ai.shop.noProductsForItem': 'No products found for this item.',
    'ai.shop.resultsVia': "Results via Serper · Click any product to view on retailer's site · Prices may vary",
    'ai.shop.downloadPDF': 'Download PDF',
    'ai.shop.downloadPdfNotice': 'Download now — your list is not saved and will not be available later.',
    'ai.loveWhatSee': 'Love what you see?',
    'ai.readyMakeReal': 'Ready to make this real?',
    'ai.firstConversation': 'First conversation is on us — no commitment needed',
    'ai.design': 'Design',
    'ai.studio': 'Studio',
    'ai.studio.desc': 'Your personal interior design assistant. Experiment with styles, visualize transformations, and find real products.',
    'ai.quiz.title': 'Style Quiz',
    'ai.quiz.desc': 'Discover your design DNA in 60 seconds.',
    'ai.vision.title': 'AI Vision',
    'ai.vision.desc': 'See your room transformed into any style instantly.',
    'ai.shop.title': 'Shopping List',
    'ai.shop.desc': 'Find real furniture from your favorite concepts.',
    'ai.signInFailed': 'Sign in failed. Please try again.',
    'ai.noGenerationsLeft': 'No generations left.',
    'ai.generationFailed': 'Generation failed. Please try again.',
    'ai.apiKeyError': 'API key permission error. Please check your key settings.',
    'ai.quotaExceeded': 'Quota exceeded. Please wait a moment and try again.',
    'ai.uploadRoomImage': 'Please upload a room image first.',
    'ai.uploadInspRoom': 'Please upload at least 1 inspiration image and your room photo',
    'ai.vision.noStyleNoRef': 'Add a reference image or pick a style to continue',
    'ai.vision.analyzing': 'Analyzing your style references\u2026',
    'ai.vision.generating': 'Generating your concept\u2026',
    'aiVision.gallery.title': 'See what\u2019s possible',
    'aiVision.gallery.subtitle': 'Same room, same inputs. Three AI interpretations.',
    'aiVision.gallery.labelRoom': 'YOUR ROOM',
    'aiVision.gallery.labelInspirations': '+ 3 INSPIRATIONS',
    'aiVision.gallery.labelConcepts': '= 3 CONCEPTS',
    'aiVision.gallery.tryItButton': 'Try a sample room \u2192',
    'aiVision.generate.helper.needPhoto': 'Upload a room photo to continue',
    'aiVision.generate.helper.needInspiration': 'Add a reference image or pick a style',
    'aiVision.inspiration.noRefsFallback': 'No references?',
    'aiVision.inspiration.noRefsFallback.link': 'Pick a style below to get started.',
    'btn.tryAi': 'Start Free — No Card Needed',
    'ai.quiz.applyStyleToRoom': 'Apply {style} to my room',

    // Multimodal Search (Design First)
    'ai.designFirst.label': 'AI-Powered Design Studio',
    'ai.designFirst.title1': 'Design First.',
    'ai.designFirst.title2': 'Commit Later.',
    'ai.designFirst.desc': 'Use our AI tools to explore possibilities before making any big decisions.',
    'ai.designFirst.tool1': 'Style Quiz — discover your design DNA',
    'ai.designFirst.tool2': 'AI Vision — see your room transformed',
    'ai.designFirst.tool3': 'Shopping List — find the real products',
    'ai.designFirst.tool4': 'Room Audit — score your current space',
    'ai.designFirst.tool5': 'Design Brief — walk in knowing what you want',
    'ai.designFirst.tool6': 'Cultural Advisor — blend global styles',
    'ai.designFirst.footerDesc': 'Then have a conversation with Anahit — and walk in already knowing what you love.',
    'ai.designFirst.rightDesc': 'Your complete starting point — style, vision, and shopping list — before you speak to anyone.',
    'ai.designFirst.freeConcepts': 'Free concepts',
    'ai.designFirst.designStyles': 'Design styles',
    'ai.designFirst.genTime': 'Generation time',
    'ai.designFirst.toExplore': 'To explore',
    'ai.designFirst.before': 'Before',

    // Testimonials
    'test.title': 'Client Stories',
    'test.heading': 'Voices of Designature',
    'test.subtext': 'What our clients say about their journey with us.',
    'testimonials.label': 'Testimonials',
    'testimonials.title': 'What Our Clients Say',
    'testimonials.desc': 'We take pride in building lasting relationships through exceptional design and dedicated service.',
    'testimonials.feedback': 'Share your feedback with us',

    // Feedback modal
    'feedback.title': 'Share your feedback',
    'feedback.type': 'Type',
    'feedback.type.general': 'General feedback',
    'feedback.type.testimonial': 'Share a testimonial',
    'feedback.type.bug': 'Report a bug',
    'feedback.type.feature': 'Request a feature',
    'feedback.name': 'Name (optional)',
    'feedback.country': 'Country (optional)',
    'feedback.email': 'Email (optional)',
    'feedback.rating': 'Rating',
    'feedback.projectType': 'Project type (optional)',
    'feedback.pt.select': '— Select —',
    'feedback.pt.residential': 'Residential',
    'feedback.pt.commercial': 'Commercial',
    'feedback.pt.other': 'Other',
    'feedback.message': 'Message *',
    'feedback.placeholder.testimonial': 'Tell us about your experience...',
    'feedback.placeholder.general': 'Tell us what you think...',
    'feedback.send': 'Send',
    'feedback.sending': 'Sending...',
    'feedback.review': 'Testimonials are reviewed before appearing on the website.',
    'feedback.thanks': 'Thank you',
    'feedback.thanksMsg': "We've received your message. We read every submission.",
    'feedback.close': 'Close',
    'feedback.error.required': 'Please write a message before submitting.',

    // Blog
    'blog.title': 'Insights',
    'blog.heading': 'Design Philosophy',
    'blog.viewAll': 'View All Articles',
    'btn.allInsights': 'All Insights',

    // CTA Banner
    'cta.banner.title': 'Ready when you are.',
    'cta.banner.subtext': "You've explored the possibilities. Let's bring your space to life — together.",
    'cta.banner.btn': "Let's talk",

    // Footer
    'footer.studio': 'Studio',
    'footer.usefulLinks': 'Useful Links',
    'footer.contacts': 'Contacts',
    'footer.newsletterHeader': 'Stay Inspired',
    'footer.emailLabel': 'Your Email Address',
    'footer.subscribe': 'Subscribe',
    'footer.submitting': 'Submitting...',
    'footer.newsletterSub': 'Join our newsletter for exclusive design insights and project updates.',
    'footer.about': 'About Us',
    'footer.terms': 'Terms of Service',
    'footer.privacy': 'Privacy Policy',
    'footer.refund': 'Refund Policy',
    'footer.usOffice': 'US Office',
    'footer.amOffice': 'Armenia Office',
    'footer.whatsappBusiness': 'WhatsApp Business',
    'footer.rights': '© 2026 Designature Studio. All Rights Reserved.',
    'footer.successTitle': 'Welcome to the Studio',
    'footer.successDesc': 'You\'ve successfully subscribed to our newsletter. Expect curated design inspiration in your inbox soon.',
    'footer.close': 'Close',
    'footer.follow': 'Follow Us',
    'footer.contact': 'Contact',
    'footer.newsletter': 'Newsletter',
    'footer.newsletterDesc': 'Subscribe to receive our latest design insights.',
    'footer.success': 'Subscribed!',

    // Header Buttons
    'btn.bookCall': "Let's Talk",
    'btn.firstConvo': 'Free — no commitment',

    // Studio Page
    'studio.heroTitle': 'The Studio',
    'studio.heroSub': "An engineer's rigor, a designer's eye. Founded in Yerevan in 2021, Designature is a boutique interior design studio — now building the tools to bring that craft to anyone, anywhere, online.",
    'studio.hero.title': 'The Studio',
    'studio.hero.desc': 'A collective of architects and designers dedicated to the art of living well.',
    'studio.aboutTitle': 'Our Story',
    'studio.aboutHeading': 'Crafting Spaces with Purpose',
    'studio.aboutDesc1': 'Designature grew out of more than a decade of working remotely with clients around the world. I started out in engineering, and it taught me that the spaces that move people are also the ones built with the most discipline. Structure and beauty were never at odds — the rigor is what lets the beauty feel effortless.',
    'studio.aboutDesc2': "That conviction is the studio's method. We listen before we draw and understand before we decide, then engineer every detail — light, proportion, material, flow — so the finished room feels inevitable rather than decorated. Since 2021 we've done this one project at a time, in Yerevan and beyond.",
    'studio.founded': 'Founded',
    'studio.projects': 'Projects Delivered',
    'studio.founderTitle': 'Founder & Engineer',
    'studio.founderRole': 'Engineer & Founding Designer',
    'studio.founder.label': 'Founder & Lead Architect',
    'studio.founder.role': 'Architect · Interior Designer',
    'studio.founder.quote': 'Design is not just what it looks like and feels like. Design is how it works.',
    'studio.founder.bio': 'With over a decade of experience across Europe and the Middle East, Anahit brings a global perspective to local craftsmanship.',
    'studio.founderQuote': "Beauty isn't something you add at the end — it's what precision looks like when it's done right.",
    'studio.founderBio': 'Anahit is an engineer turned interior designer. After more than a decade working remotely with international clients, she founded Designature in 2021 — bringing that blend of technical rigor and design instinct to homes across Armenia and beyond, and now to anyone online.',
    'studio.story.title': 'Our Story & Philosophy',
    'studio.story.p1': 'Founded in 2021, Designature was born from a simple belief: that the spaces we inhabit profoundly shape the quality of our lives.',
    'studio.story.p2': 'We don\'t believe in "styles" as fixed rules. We believe in signatures — the unique intersection of a client\'s personality and the architectural potential of a site.',
    'studio.story.p3': "Now we're taking that craft online. Great interior design has always meant hiring a studio; we're building an AI-powered layer — room visualizations, style direction, curated sourcing — so anyone can start with a designer's thinking today, and step up to the full studio when they're ready.",
    'studio.contactHeading': 'Let\'s Connect',
    'studio.contactSub': 'Whether you have a fully formed vision or just the seed of an idea, we\'re here to help you grow it.',
    'studio.contact.title': 'Get in touch',
    'studio.contact.hero': 'Let\'s build something remarkable',
    'studio.contact.desc': 'Have a project in mind? We\'d love to hear about it. Our team is ready to help you bring your vision to life.',
    'studio.contact.email': 'Email',
    'studio.contact.phone': 'Phone',
    'studio.contact.location': 'Studio',
    'studio.contact.location.desc': 'Yerevan, Armenia and Worldwide',
    'studio.contact.form.title': 'Send us a message',
    'studio.contact.form.name': 'Your full name',
    'studio.contact.form.email': 'your@email.com',
    'studio.contact.form.subject': 'Living room redesign · 120m²',
    'studio.contact.form.message': 'Tell us about your project, timeline, vision…',
    'studio.contact.form.success': 'Message sent successfully!',
    'studio.contact.form.error': 'Failed to send message. Please try again.',
    'studio.emailUs': 'Email Us',
    'studio.callUs': 'Call Us',
    'studio.visitUs': 'Visit Us',
    'studio.formName': 'Full Name',
    'studio.formEmail': 'Email Address',
    'studio.formSubject': 'Subject',
    'studio.formMessage': 'Your Message',
    'studio.formSend': 'Send Message',
    'studio.formSending': 'Sending...',
    'studio.formSuccess': 'Message Sent Successfully',
    'studio.formError': 'Error Sending Message',

    // AI Vision Page
    'ai.vision.hero': 'AI Vision',
    'ai.vision.heroDesc': 'We don\'t use AI to replace the architect. We use it to augment the human imagination and eliminate technical friction.',
    'ai.vision.back': 'BACK TO HOME',
    'ai.vision.point1.title': 'Hyper-Personalization',
    'ai.vision.point1.desc': 'AI that learns your subconscious aesthetic preferences to suggest spaces you didn\'t know you needed.',
    'ai.vision.point2.title': 'Real-time Iteration',
    'ai.vision.point2.desc': 'Instantly visualize structural changes, material swaps, and lighting scenarios during our design sessions.',
    'ai.vision.point3.title': 'Predictive Engineering',
    'ai.vision.point3.desc': 'Advanced algorithms that predict structural longevity and energy efficiency before the first brick is laid.',
    'ai.vision.point4.title': 'Ethical Automation',
    'ai.vision.point4.desc': 'Using technology to handle the mundane, freeing our architects to focus purely on the soul and art of your project.',
    'ai.vision.quote': 'The algorithm of beauty is human.',
    'ai.vision.cta': 'Learn about our philosophy',

    // General Buttons
    'btn.generate': 'Generate concept',
    'btn.download': 'Download',
    'btn.book': "Let's Talk",
    'btn.back': 'Back',
    'btn.next': 'Next',
    'btn.close': 'Close',
    'btn.send': 'Send',

    // Pricing Section (full)
    'pricing.backHome': 'Back to Home',
    'pricing.hero': 'Pricing',
    'pricing.subtitle': 'Start free — no card needed. Buy credits when you need them, or subscribe monthly.',
    'pricing.eyebrow': 'Pricing',
    'pricing.title': 'Simple, honest pricing.',
    'pricing.subtitle2': "Start free — 50 credits, no card.\nBuy more when you're ready.",
    'pricing.free.badge': 'Free',
    'pricing.free.forever': '/ forever',
    'pricing.free.desc': 'Try the full AI journey before spending anything. No credit card needed.',
    'pricing.aiTools': 'AI Tools',
    'pricing.free.ctaFull': 'Start free — no card needed',
    'pricing.free.note': 'Concepts not saved after session',
    'pricing.unlimited': 'unlimited',
    'pricing.3concepts': '3 concepts',
    'pricing.perConceptPDF': 'per concept + PDF',
    'pricing.popular': 'Most Popular',
    'pricing.month': '/ month',
    'pricing.design.desc': 'For homeowners actively working on one space.',
    'pricing.everything.free': 'Everything in Free',
    'pricing.everything.design': 'Everything in Design',
    'pricing.30credits': '30 credits / month',
    'pricing.20month': '20 / month',
    'pricing.budgetFilter': 'budget filter',
    'pricing.3month': '3 / month',
    'pricing.1month': '1 / month',
    'pricing.300month': '300 / month',
    'pricing.studio.desc': 'For designers or anyone renovating multiple spaces.',
    'pricing.inclCultural': 'incl. Cultural Advisor',
    'pricing.projectFolders': 'Project folders',
    'pricing.saveConcepts': 'save concepts & images per project',
    'pricing.notify': 'Notify me when live',
    'pricing.notify.sent': "✓ Got it — we'll notify you",
    'pricing.notify.btn': 'Notify me',

    // S-013 Home narrative — Section 1 (Hero text)
    'home.hero.eyebrow': 'Online interior design studio',
    'home.hero.headline.l1': 'Bring us a space.',
    'home.hero.headline.l2': "We'll bring it to life.",
    'home.hero.tagline': "Apartments. Houses. Commercial. Designature Studio designs the space you've imagined — and the parts you haven't yet.",

    // Section 2 (Image band)
    'home.band.apartments.cat': 'Apartments',
    'home.band.apartments.cap': 'Where you actually live.',
    'home.band.houses.cat': 'Houses',
    'home.band.houses.cap': 'From foundations to finishes.',
    'home.band.commercial.cat': 'Commercial',
    'home.band.commercial.cap': 'Where customers come back.',

    // Section 3 (How it works)
    'home.how.eyebrow': 'How we work together',
    'home.how.headline': 'From first idea to finished space.',
    'home.how.s1.title': 'Explore',
    'home.how.s1.desc': 'Understand your taste and try ideas on your space — at your own pace.',
    'home.how.s1.tools': 'Style Quiz · AI Vision · Portfolio',
    'home.how.s2.title': 'Consult',
    'home.how.s2.desc': "A 45-minute paid call with the studio. Review what you've explored, your space, your budget, your timeline.",
    'home.how.s2.tools': 'Book · Calendly',
    'home.how.s3.title': 'Design',
    'home.how.s3.desc': 'The studio develops concepts, drawings, and material specifications tailored to your project.',
    'home.how.s3.tools': 'Concept · Drawings · Materials',
    'home.how.s4.title': 'Realize',
    'home.how.s4.desc': "We oversee execution and handover. You move in to a space that's truly yours.",
    'home.how.s4.tools': 'Execution · Handover',
    'home.how.cta': "See what you'll receive →",
    'home.how.ctaSub': 'Sample design brief · PDF',

    // Section 4 (Featured Work)
    'home.work.eyebrow': 'Selected projects',
    'home.work.headline': 'Recent work.',
    'home.work.cta': 'View full portfolio →',
    'home.work.locApartmentYerevan': 'Apartment · Yerevan',
    'home.work.locHouseYerevan': 'House · Yerevan',
    'home.work.locApartment': 'Apartment',
    'home.work.locHouse': 'House',
    'home.work.locCommercial': 'Commercial',

    // Section 5 (AI tools)
    // S-013 AI section v3.1 (Hero Demo + Tool Strip + Roadmap Ribbon + CTAs)
    'home.ai.eyebrow': 'AI Studio · 4 tools live · more coming',
    'home.ai.headline.l1': 'Explore your space.',
    'home.ai.headline.l2': 'Tools made for real projects.',
    'home.ai.lead': "Try AI Vision, Style Quiz, Shopping List, and Room Audit — designed by us, built around how you'd actually plan a real space.",
    'home.ai.demoBefore': 'Before',
    'home.ai.demoAfter': 'After · AI Vision',
    'home.ai.tools.styleQuiz.title': 'Style Quiz',
    'home.ai.tools.styleQuiz.desc': 'Discover your interior style in 2 minutes.',
    'home.ai.tools.aiVision.title': 'AI Vision',
    'home.ai.tools.aiVision.desc': 'Transform your room with AI in seconds.',
    'home.ai.tools.shoppingList.title': 'Shopping List',
    'home.ai.tools.shoppingList.desc': 'Identify and shop every product in any room.',
    'home.ai.tools.roomAudit.title': 'Room Audit',
    'home.ai.tools.roomAudit.desc': 'Score your room on key design metrics.',
    'home.ai.featuredBadge': 'Most Popular',
    'home.ai.tier.free': 'Free',
    'home.ai.tier.designPlus': 'Design+',
    'home.ai.tier.unlimited': 'Unlimited',
    'home.ai.tier.aiVisionCount': '3 concepts / mo',
    'home.ai.tier.shoppingListCount': '3 lists / mo · PDF',
    'home.ai.tier.roomAuditCount': '3 audits / mo',
    'home.ai.comingSoonLabel': 'Coming soon',
    'home.ai.comingSoonItems': 'Floorplan Generator · Lighting Planner · Electrical Plan · 3D Walkthrough · Material Moodboard · Budget Estimator · Renovation Sequencer',
    'home.ai.cta.tryFree': 'Try AI free →',
    'home.ai.cta.browseAll': 'Browse all tools →',

    // Section 6 (Voices)
    'home.voices.eyebrow': 'From our clients',
    'home.voices.headline': 'Voices.',
    'home.voices.q1': '"Designature Studio was great to work with — super responsive and delivered quality renderings. Highly recommended."',
    'home.voices.q1source': 'Verified client',
    'home.voices.q2': '"They iterate until the client is fully satisfied — something genuinely praiseworthy."',
    'home.voices.q2source': 'Verified client',
    'home.voices.q3': '"2nd project with Designature Studio and they did a great job. Thank you."',
    'home.voices.q3source': 'Repeat client',

    // Section 7 (Closing)
    'home.closing.eyebrow': 'Your move',
    'home.closing.headline': 'Two ways forward.',
    'home.closing.sub': 'Explore your space with AI. Or sit down with the studio. Same destination.',
    'home.closing.ai.label': 'Try AI free →',
    'home.closing.ai.sub': 'Explore on your own',
    'home.closing.book.label': 'Book a consultation →',
    'home.closing.book.sub': 'Sit down with the studio',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  // Locked to English — Armenian dropped 2026-08-27. No setter exposed.
  const language: Language = 'en';
  const location = useLocation();
  const navigate = useNavigate();

  const { page: currentPage, projectId: urlProjectId } = pathToPageState(location.pathname);

  const queryFilter = new URLSearchParams(location.search).get('filter');
  const portfolioFilter: PortfolioFilter =
    queryFilter === 'Residential' || queryFilter === 'Commercial' ? queryFilter : 'All';

  // Scroll to top on every route change (matches the old setCurrentPage behavior).
  useEffect(() => {
    window.scrollTo(0, 0);
  }, [location.pathname]);

  const t = (key: string) => {
    return translations.en[key as keyof typeof translations.en] || key;
  };

  // In-flight-work guard. A ref (not state) so reads are always current and setting
  // it never re-renders. When set, leaving the current page asks for confirmation.
  const navGuardRef = useRef<string | null>(null);
  const setNavGuard = (message: string | null) => { navGuardRef.current = message; };
  const confirmNav = () => {
    const message = navGuardRef.current;
    if (!message) return true;
    return window.confirm(message);
  };

  const navigateTo = (page: Page, projectId?: string, filter?: PortfolioFilter) => {
    const target = pageToPath(page, projectId, filter);
    // Only guard real page changes — re-selecting the current page shouldn't prompt.
    if (target !== location.pathname && !confirmNav()) return;
    navigate(target);
  };

  // Backwards-compat shims: existing call sites do `setSelectedProjectId(id)` then
  // `navigateTo('project-detail')`. We make `setSelectedProjectId` navigate
  // straight to /portfolio/:id so the second call becomes a no-op (same URL).
  const setSelectedProjectId = (id: string | null) => {
    if (id) navigate(pageToPath('project-detail', id));
    else if (currentPage === 'project-detail') navigate(pageToPath('portfolio'));
  };

  const setPortfolioFilter = (filter: PortfolioFilter) => {
    navigate(pageToPath('portfolio', undefined, filter));
  };

  return (
    <LanguageContext.Provider value={{
      language,
      t,
      currentPage,
      selectedProjectId: urlProjectId,
      setSelectedProjectId,
      portfolioFilter,
      setPortfolioFilter,
      navigateTo,
      setNavGuard,
      confirmNav,
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
